--PART – A:
--1. INSERT PROCEDURES: CREATE STORED PROCEDURES TO INSERT RECORDS INTO STUDENT TABLES
--(SP_INSERT_STUDENT)
--	STDID	SNAME	CITY	SPI		BRANCH 
--	115		PUSHTI	RAJKOT	9.48	COMPUTER
--	116		NIKUNJ	SURAT	8.80	CHEMICAL 

 CREATE PROCEDURE PR_INSERT_STUDENT
 @STDID INT ,
 @SNAME VARCHAR(30),
 @CITY VARCHAR(30),
 @SPI DECIMAL(4,2) ,
 @BRANCH VARCHAR(30)
 AS 
 BEGIN
	INSERT INTO STUDENT VALUES (@STDID , @SNAME , @CITY , @SPI , @BRANCH)
 END

 EXEC PR_INSERT_STUDENT 115 , 'PUSHTI' , 'RAJKOT' , 9.48 ,  'COMPUTER'
 EXEC PR_INSERT_STUDENT 116 , 'NIKUNJ' , 'SURAT' , 8.80 ,  'CHEMICAL'

 SELECT * FROM STUDENT

 
	


--2. INSERT PROCEDURES: CREATE STORED PROCEDURES TO INSERT RECORDS INTO DEPOSIT TABLES
--(SP_INSERT_DEPOSIT)
--	ACTNO	CNAME	BNAME	AMOUNT	ADATE
--	118		HEMENT	BEDI	16000	05-05-2025
--	119		RAVI	MAVDI	24000	09-07-2024 


 CREATE PROCEDURE PR_INSERT_DEPOSIT
 @ACTNO INT ,
 @CNAME VARCHAR(30),
 @BNAME VARCHAR(30),
 @AMOUNT INT ,
 @ADATE DATETIME
 AS 
 BEGIN
	INSERT INTO DEPOSIT VALUES (@ACTNO , @CNAME , @BNAME , @AMOUNT , @ADATE)
 END

 EXEC PR_INSERT_DEPOSIT 118 , 'HEMENT' , 'BEDI' , 16000 ,  '05-05-2025'
 EXEC PR_INSERT_DEPOSIT 119 , 'RAVI' , 'MAVDI' , 24000 ,  '09-07-2024'

 SELECT * FROM DEPOSIT



--3.UPDATE PROCEDURES: CREATE STORED PROCEDURE SP_UPDATE_STUDENT TO UPDATE BRANCH IN STUDENT
--TABLE. (UPDATE USING STUDENTID) 

	--STDID	BRANCH	
	--115		ELECTRICAL
	--116		MECHANICAL 

CREATE PROCEDURE PR_UPDATE_STUDENT
 @STDID INT ,
 @BRANCH VARCHAR(30)
 AS 
 BEGIN
	UPDATE STUDENT
	SET BRANCH = @BRANCH
	WHERE STDID = @STDID
 END

 EXEC PR_UPDATE_STUDENT @STDID = 115 , @BRANCH = 'ELECTRICAL'
 EXEC PR_UPDATE_STUDENT @STDID = 116 , @BRANCH = 'MECHANICAL'

 SELECT * FROM STUDENT

--	4. DELETE PROCEDURES: CREATE STORED PROCEDURE SP_DELETE_STUDENT TO DELETE RECORDS FROM STUDENT
--WHERE STUDENT NAME IS RAVI.

CREATE PROCEDURE PR_DELETE_STUDENT
 @SNAME VARCHAR(30)
 AS 
 BEGIN
	DELETE STUDENT
	WHERE SNAME = @SNAME
 END

 EXEC PR_DELETE_STUDENT 'RAVI'


 SELECT * FROM STUDENT

--5. SELECT BY PRIMARY KEY: CREATE STORED PROCEDURES TO SELECT RECORDS BY PRIMARY KEY
--(SP_SELECT_STUDENT_BY_ID) FROM STUDENT TABLE. (DISPLAY ALL COLUMNS)

CREATE PROCEDURE PR_SELECT_STUDENT_BY_ID
 @ID INT
 AS 
 BEGIN
	SELECT * FROM STUDENT
	WHERE STDID = @ID
 END

 EXEC PR_SELECT_STUDENT_BY_ID 101

 SELECT * FROM STUDENT


--6. CREATE A STORED PROCEDURE THAT SHOWS DETAILS OF THE FIRST 5 STUDENTS ORDERED BY SPI (HIGHEST FIRST). 


CREATE PROCEDURE PR_HIGEST_FIRST
 AS 
 BEGIN
	SELECT TOP 5 * FROM STUDENT
	ORDER BY SPI DESC
	
 END

 EXEC PR_HIGEST_FIRST
 SELECT * FROM STUDENT


--FROM THE TABLE EMPLOYEE PERFORM THE FOLLOWING QUERIES:
--PART – B:
--7. CREATE A STORED PROCEDURE WHICH DISPLAYS ALL EMPLOYEE DETAILS.

CREATE PROCEDURE PR_DISPLAY_EMPLOYEE
AS
BEGIN
	SELECT * FROM EMPLOYEE
END

EXEC PR_DISPLAY_EMPLOYEE


--8. CREATE A STORED PROCEDURE THAT TAKES DEPARTMENT NAME AS INPUT AND RETURNS ALL THE EMPLOYEE IN THAT
--DEPARTMENT. 

CREATE PROCEDURE PR_DEPARTEMENT_EMP
@DEPARTMENT VARCHAR(30)
AS
BEGIN
	SELECT * FROM EMPLOYEE
	WHERE DEPARTMENT = @DEPARTMENT
END

EXEC PR_DEPARTEMENT_EMP 'IT'



--PART – C:
--9. CREATE A STORED PROCEDURE WHICH DISPLAYS DEPARTMENT-WISE MAXIMUM, MINIMUM, AND AVERAGE SALARY OF
--EMPLOYEE.

CREATE PROCEDURE PR_MAX_MIN_AVG_SALARY
AS
BEGIN
	SELECT DEPARTMENT , MAX(SALARY) AS MAX_SALARY , MIN(SALARY) AS MIN_SALARY , AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE
	GROUP BY DEPARTMENT
END

EXEC PR_MAX_MIN_AVG_SALARY


--10. CREATE A STORED PROCEDURE THAT ACCEPTS DEPARTMENT NAME AS PARAMETER AND RETURNS TOTAL SALARY OF THEIR
--DEPARTMENT. 

CREATE PROCEDURE PR_DEPARTEMENT_WISE_TOTAL_SALARY
@DEPARTMENT VARCHAR(30)
AS
BEGIN
	SELECT DEPARTMENT , SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE
	WHERE DEPARTMENT = @DEPARTMENT
	GROUP BY DEPARTMENT

END

EXEC PR_DEPARTEMENT_WISE_TOTAL_SALARY 'HR'


