CREATE TABLE Customers ( 
CustomerID INT PRIMARY KEY, 
CustomerName VARCHAR (100) NOT NULL, 
City VARCHAR (100), 
Membership VARCHAR (20) 
); 


INSERT INTO Customers (CustomerID, CustomerName, City, Membership) VALUES 
(101, 'Alice', 'Mumbai', 'Gold'), 
(102, 'Bob', 'Delhi', 'Silver'), 
(103, 'Charlie', 'Pune', 'Gold'), 
(104, 'David', 'Ahmedabad', 'Silver'), 
(105, 'Eva', 'Mumbai', 'Platinum');


CREATE TABLE Orders ( 
OrderID INT PRIMARY KEY, 
CustomerID INT NOT NULL, 
Product VARCHAR (100) NOT NULL, 
Category VARCHAR (50), 
Quantity INT NOT NULL, 
Price DECIMAL (10,2) NOT NULL, 
FOREIGN KEY (CustomerID) REFERENCES Customers (CustomerID) 
);


INSERT INTO Orders (OrderID, CustomerID, Product, Category, Quantity, Price) 
VALUES 
(201, 101, 'Laptop', 'Electronics', 1, 70000), 
(202, 101, 'Mouse', 'Electronics', 2, 800), 
(203, 102, 'Chair', 'Furniture', 3, 2500), 
(204, 103, 'Phone', 'Electronics', 1, 45000), 
(205, 104, 'Table', 'Furniture', 2, 6000), 
(206, 105, 'Laptop', 'Electronics', 2, 70000), 
(207, 105, 'Printer', 'Electronics', 1, 12000), 
(208, 103, 'Desk', 'Furniture', 1, 8000); 


SELECT * FROM Customers
SELECT * FROM Orders



--1) CREATE A VIEW NAMED CUSTOMERORDERS DISPLAYING: 
--• CUSTOMER NAME 
--• CITY 
--• PRODUCT 
--• CATEGORY 
--• QUANTITY 
--• PRICE 

CREATE VIEW CUSTOMERORDERS
AS
SELECT C.CustomerName , C.City , O.Product , O.Category , O.Quantity , O.Price 
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID

SELECT * FROM CUSTOMERORDERS

--2) CREATE A VIEW NAMED GOLDCUSTOMERSORDERS THAT DISPLAYS ALL ORDERS PLACED BY GOLD 
--MEMBERS. 

CREATE OR ALTER VIEW GOLDCUSTOMERSORDERS
AS
SELECT C.CustomerName , C.Membership , O.Product
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
WHERE C.Membership = 'GOLD'
SELECT * FROM GOLDCUSTOMERSORDERS

--3) CREATE A VIEW ELECTRONICORDERS DISPLAYING ONLY ELECTRONICS ORDERS.

CREATE OR ALTER VIEW ELECTRONICORDERS
AS
SELECT C.CustomerName , C.Membership , O.Product , O.Category
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
WHERE O.Category = 'ELECTRONICS'
SELECT * FROM ELECTRONICORDERS
--4) CREATE A VIEW CUSTOMERPURCHASESUMMARY SHOWING THE TOTAL PURCHASE AMOUNT FOR 
--EACH CUSTOMER. 
--(PURCHASE AMOUNT = QUANTITY * PRICE) 

CREATE OR ALTER VIEW CUSTOMERPURCHASESUMMARY
AS
SELECT C.CustomerName , SUM(O.Price * O.Quantity) AS TOTAL
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerName
SELECT * FROM CUSTOMERPURCHASESUMMARY
--5) CREATE A VIEW CUSTOMERORDERCOUNT SHOWING: 
--• CUSTOMER NAME 
--• NUMBER OF ORDERS PLACED 

CREATE OR ALTER VIEW CUSTOMERORDERCOUNT
AS
SELECT C.CustomerName , COUNT(O.OrderID) AS COUNT_C 
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerName
SELECT * FROM CUSTOMERORDERCOUNT
--6) CREATE A VIEW CATEGORYSALES DISPLAYING: 
--• CATEGORY 
--• NUMBER OF ORDERS 
--• TOTAL QUANTITY SOLD 


CREATE OR ALTER VIEW CATEGORYSALES
AS
SELECT O.Category , COUNT(O.OrderID) AS COUNT_C  , SUM(O.Quantity) AS SOLD
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY O.Category
SELECT * FROM CATEGORYSALES
--7) CREATE A VIEW AMOUNTDETAILS DISPLAYING: 
--• MEMBERSHIP TYPE 
--• AVERAGE PURCHASE AMOUNT PER ORDER  

CREATE OR ALTER VIEW AMOUNTDETAILS
AS
SELECT C.Membership , AVG(O.Price * O.Quantity) AS AVG_PURCH
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.Membership
SELECT * FROM AMOUNTDETAILS
--8) CREATE A VIEW CITYSALES DISPLAYING: 
--• CITY 
--• TOTAL CUSTOMERS WHO PLACED ORDERS 
--• TOTAL PURCHASE AMOUNT 


CREATE OR ALTER VIEW CITYSALES
AS
SELECT C.City , SUM(O.OrderID) AS ORDER_ , SUM(O.Price * O.Quantity) AS AMOUNT
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.City
SELECT * FROM CITYSALES
--9) CREATE A VIEW CUSTOMERSALES DISPLAYING: 
--• CUSTOMER NAME 
--• MEMBERSHIP 
--• TOTAL QUANTITY PURCHASED 
--• TOTAL AMOUNT SPENT 

CREATE OR ALTER VIEW CUSTOMERSALES
AS
SELECT C.CustomerName ,C.Membership , SUM(O.Quantity) AS QUA , SUM(O.Price*O.Quantity) AS TOTAL_AMOUNT
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerName , C.Membership
SELECT * FROM CUSTOMERSALES
--10) CREATE A VIEW CUSTOMERMEMBERSHIP DISPLAYING: 
--• CATEGORY 
--• MEMBERSHIP TYPE 
--• TOTAL SALES 
--• AVERAGE QUANTITY PURCHASed

CREATE OR ALTER VIEW CUSTOMERMEMBERSHIP
AS
SELECT O.Category , C.Membership , SUM(O.Price * O.Quantity) AS SALES , AVG(O.Quantity) AS AVG_Q
FROM Customers C
INNER JOIN
Orders O
ON C.CustomerID = O.CustomerID
GROUP BY O.Category , C.Membership
SELECT * FROM CUSTOMERMEMBERSHIP