--FROM THE TABLE EMPLOYEE PERFORM THE FOLLOWING QUERIES: 

SELECT * FROM EMPLOYEE

--PART – A: 
--1. CREATE A VIEW EMPLOYEE_ALL WITH ALL COLUMNS.

CREATE VIEW EMPLOYEE_ALL
AS 
SELECT * FROM EMPLOYEE
SELECT * FROM EMPLOYEE_ALL

--2. CREATE A VIEW EMPLOYEE_NAMEDEPTSALARY HAVING COLUMNS FIRSTNAME, DEPARTMENT AND SALARY.

CREATE VIEW EMPLOYEE_NAMEDEPTSALARY
AS
SELECT FIRSTNAME,DEPARTMENT,SALARY FROM EMPLOYEE

SELECT * FROM EMPLOYEE_NAMEDEPTSALARY
--3. CREATE A VIEW EMPLOYEE_BASIC HAVING COLUMNS EID, FIRSTNAME AND CITY. 


CREATE VIEW EMPLOYEE_BASIC
AS
SELECT EID,FIRSTNAME,CITY FROM EMPLOYEE

SELECT * FROM EMPLOYEE_BASIC

--4. CREATE A VIEW IT_EMPLOYEES THAT DISPLAYS IT DEPARTMENT DATA ONLY.

CREATE VIEW IT_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'IT'
SELECT * FROM IT_EMPLOYEES

--5. CREATE A VIEW HR_EMPLOYEES THAT DISPLAYS HR DEPARTMENT DATA ONLY.

CREATE VIEW HR_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'
SELECT * FROM HR_EMPLOYEES
--6. CREATE A VIEW EMPLOYEE_2026 THAT DISPLAYS EMPLOYEES JOINED IN 2026 ONLY. 

CREATE VIEW EMPLOYEE_2026
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR = 2026
SELECT * FROM EMPLOYEE_2026
--7. CREATE A VIEW PATEL_EMPLOYEES THAT DISPLAYS EMPLOYEES WHOSE LAST NAME IS PATEL.

CREATE VIEW PATEL_EMPLOYEES
AS 
SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'PATEL'
SELECT * FROM PATEL_EMPLOYEES
--8. CREATE A VIEW HIGH_SALARY_EMP HAVING ALL COLUMNS BUT EMPLOYEES WHOSE SALARY IS MORE THAN 12000.


CREATE VIEW HIGH_SALARY_EMP
AS 
SELECT * FROM EMPLOYEE
WHERE SALARY > 12000
SELECT * FROM HIGH_SALARY_EMP
--9. CREATE A VIEW THAT DISPLAYS INFORMATION OF ALL EMPLOYEES WHOSE SALARY IS ABOVE 14000. 

CREATE VIEW HIGH_SALARY
AS 
SELECT * FROM EMPLOYEE
WHERE SALARY > 14000
SELECT * FROM HIGH_SALARY
--10. CREATE A VIEW THAT DISPLAYS EMPLOYEES HAVING SALARY BELOW 10000.

CREATE VIEW LOW_SALARY
AS 
SELECT * FROM EMPLOYEE
WHERE SALARY < 10000
SELECT * FROM LOW_SALARY
--11. CREATE A VIEW SERVER_DEPT THAT DISPLAYS SERVER DEPARTMENT EMPLOYEES ONLY.


CREATE VIEW SERVER_DEPT
AS 
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'SERVER'
SELECT * FROM SERVER_DEPT
--12. INSERT A NEW RECORD INTO EMPLOYEE_BASIC VIEW. (111, MEET, SURAT) 

INSERT INTO EMPLOYEE_BASIC(EID , FIRSTNAME , CITY)
VALUES (111 ,'MEET','SURAT')

SELECT * FROM EMPLOYEE_BASIC
--13. UPDATE THE DEPARTMENT OF DEEP FROM ADMIN TO IT IN EMPLOYEE_NAMEDEPTSALARY VIEW. 

UPDATE EMPLOYEE_NAMEDEPTSALARY
SET DEPARTMENT = 'IT'
WHERE FIRSTNAME = 'DEEP'

SELECT * FROM EMPLOYEE_NAMEDEPTSALARY
--14. DELETE AN EMPLOYEE WHOSE EID IS 107 FROM EMPLOYEE_BASIC VIEW.

DELETE FROM EMPLOYEE_BASIC
WHERE EID = 107


SELECT * FROM EMPLOYEE_BASIC
--15. DROP IT_EMPLOYEES VIEW FROM THE DATABASE.

DROP VIEW IT_EMPLOYEES
 
--PART – B: 
--16. CREATE A VIEW ADMIN_EMPLOYEES THAT DISPLAYS ADMIN DEPARTMENT EMPLOYEES ONLY.

CREATE VIEW ADMIN_EMPLOYEES
AS 
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'ADMIN'

SELECT * FROM ADMIN_EMPLOYEES
--17. CREATE A VIEW FEMALE_EMPLOYEES THAT DISPLAYS FEMALE EMPLOYEE DATA ONLY.
CREATE VIEW FEMALE_EMPLOYEES
AS 
SELECT * FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
SELECT * FROM FEMALE_EMPLOYEES


--18. CREATE A VIEW MALE_EMPLOYEES THAT DISPLAYS MALE EMPLOYEE DATA ONLY.

CREATE VIEW MALE_EMPLOYEES
AS 
SELECT * FROM EMPLOYEE
WHERE GENDER = 'MALE'
SELECT * FROM MALE_EMPLOYEES
--19. CREATE A VIEW RAJKOT_EMPLOYEES THAT DISPLAYS EMPLOYEES FROM RAJKOT CITY ONLY.

CREATE VIEW RAJKOT_EMPLOYEES
AS 
SELECT * FROM EMPLOYEE
WHERE CITY = 'RAJKOT'
SELECT * FROM RAJKOT_EMPLOYEES
--20. CREATE A VIEW AHMEDABAD_EMPLOYEES THAT DISPLAYS EMPLOYEES FROM AHMEDABAD CITY ONLY.

CREATE VIEW AHMEDABAD_EMPLOYEES
AS 
SELECT * FROM EMPLOYEE
WHERE CITY = 'AHMEDABAD'
SELECT * FROM AHMEDABAD_EMPLOYEES
--21. CREATE A VIEW SALARY_BETWEEN THAT DISPLAYS EMPLOYEES WHOSE SALARY IS BETWEEN 10000 AND 14000. 

CREATE VIEW SALARY_BETWEEN
AS 
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 10000 AND 14000
SELECT * FROM SALARY_BETWEEN
--22. CREATE A VIEW RECENT_EMPLOYEES THAT DISPLAYS EMPLOYEES JOINED AFTER 2023.

CREATE VIEW RECENT_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR > 2023
SELECT * FROM RECENT_EMPLOYEES
--23. CREATE A VIEW OLD_EMPLOYEES THAT DISPLAYS EMPLOYEES JOINED BEFORE 2023.

CREATE VIEW OLD_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR < 2023
SELECT * FROM OLD_EMPLOYEES
--24. CREATE A VIEW EMPLOYEES_START_R THAT DISPLAYS EMPLOYEES WHOSE FIRST NAME STARTS WITH R. 

CREATE VIEW EMPLOYEES_START_R
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'R%'

SELECT * FROM EMPLOYEES_START_R
--25. CREATE A VIEW EMPLOYEES_END_A THAT DISPLAYS EMPLOYEES WHOSE FIRST NAME ENDS WITH A. 

CREATE VIEW EMPLOYEES_END_A
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%A'

SELECT * FROM EMPLOYEES_END_A
 
--PART – C: 
--26. CREATE A VIEW EMPLOYEES_NAMECONTAINS_H THAT DISPLAYS EMPLOYEES WHOSE FIRST NAME CONTAINS H.

CREATE VIEW EMPLOYEES_NAMECONTAINS_H
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%H%'

SELECT * FROM EMPLOYEES_NAMECONTAINS_H
--27. CREATE A VIEW FOR THE EMPLOYEES WHOSE FIRST NAME CONTAINS VOWELS.

CREATE VIEW EMPLOYEES_NAMEVOWEL
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%[AEIOU]%'

SELECT * FROM EMPLOYEES_NAMEVOWEL


--28. CREATE A VIEW FOURLETTER_NAME HAVING EID, FIRSTNAME AND DEPARTMENT COLUMNS IN WHICH FIRSTNAME 
--CONSISTS OF FOUR LETTERS. 

CREATE VIEW FOURLETTER_NAME
AS
SELECT EID, FIRSTNAME , DEPARTMENT FROM EMPLOYEE
WHERE FIRSTNAME LIKE '____'

SELECT * FROM FOURLETTER_NAME
--29. CREATE A VIEW FOR THE EMPLOYEES WHOSE NAME STARTS WITH M AND ENDS WITH N. 

CREATE VIEW EMPLOYEES_STARM_ENFN
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'M%H'

SELECT * FROM EMPLOYEES_STARM_ENFN

--30. CREATE A VIEW TRANSPORT_DEPT THAT DISPLAYS TRANSPORT DEPARTMENT EMPLOYEES ONLy.

CREATE VIEW TRANSPORT_DEPT
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'TRANSPORT'

SELECT * FROM TRANSPORT_DEPT