SELECT * FROM EMPLOYEE

--1. DISPLAY THE HIGHEST, LOWEST SALARY AND LABEL THE COLUMNS MAXIMUM, MINIMUM RESPECTIVELY. 

SELECT MAX(SALARY) AS MAXIMUM , MIN(SALARY) AS MINIMUM 
FROM EMPLOYEE

--2. DISPLAY TOTAL, AND AVERAGE SALARY OF ALL EMPLOYEES. LABEL THE COLUMNS TOTAL_SAL AND AVERAGE_SAL, 
--RESPECTIVELY.

SELECT SUM(SALARY) AS TOTAL_SAL , AVG(SALARY) AS AVERAGE_SAL 
FROM EMPLOYEE
--3. FIND TOTAL NUMBER OF EMPLOYEES OF EMPLOYEE TABLE.
SELECT COUNT(EID) AS TOTAL_EMPLOYEE 
FROM EMPLOYEE

--4. FIND HIGHEST SALARY FROM RAJKOT CITY.

SELECT MAX(SALARY) AS RAJKOT_SALARY 
FROM EMPLOYEE
WHERE CITY = 'RAJKOT'
--5. GIVE MAXIMUM SALARY FROM IT DEPARTMENT. 

SELECT MAX(SALARY) AS IT_SALARY 
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT'

--6. COUNT EMPLOYEE DEPARTMENT IS HR. 

SELECT COUNT(EID) AS HR_DEPARTMENT 
FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'
--7. DISPLAY AVERAGE SALARY OF ADMIN DEPARTMENT. 

SELECT AVG(SALARY) AS ADMIN_AVG_SALARY 
FROM EMPLOYEE
WHERE DEPARTMENT = 'ADMIN';
--8. DISPLAY TOTAL SALARY OF HR DEPARTMENT.

SELECT SUM(SALARY) AS TOTAL_SALARY_HR 
FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'
--9. COUNT TOTAL NUMBER OF CITIES OF EMPLOYEE WITHOUT DUPLICATION. 

SELECT COUNT(DISTINCT CITY) AS DIST_CITY 
FROM EMPLOYEE
--10. COUNT UNIQUE DEPARTMENTS. 

SELECT COUNT(DISTINCT DEPARTMENT) AS DIST_DEPARTMENTS 
FROM EMPLOYEE 
--11. DISPLAY MINIMUM SALARY OF EMPLOYEE WHO BELONGS TO AHMEDABAD.

SELECT MIN(SALARY) AS MIN_SALARY_AHMDA 
FROM EMPLOYEE
WHERE CITY = 'AHMEDABAD'
--12. FIND CITY WISE HIGHEST SALARY.

SELECT CITY , MAX(SALARY) AS CITY_WISE_MAX 
FROM EMPLOYEE
GROUP BY CITY
--13. FIND DEPARTMENT WISE LOWEST SALARY. 

SELECT DEPARTMENT , MIN(SALARY) AS MIN_SALARY_DEPA_WISE 
FROM EMPLOYEE
GROUP BY DEPARTMENT
--14. DISPLAY MINIMUM SALARY IN EACH CITY. 

SELECT CITY , MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEE
GROUP BY CITY
--15. DISPLAY AVERAGE SALARY OF EMPLOYEES FROM SURAT.

SELECT AVG(SALARY) AS SURAT_AVG_SALARY 
FROM EMPLOYEE
WHERE CITY = 'SURAT'
--16. DISPLAY TOTAL SALARY OF FEMALE EMPLOYEES. 

SELECT SUM(SALARY) AS FEMALE_SALARY 
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
--17. COUNT NUMBER OF MALE EMPLOYEES. 

SELECT COUNT(EID) AS MALE_COUNT
FROM EMPLOYEE
WHERE GENDER = 'MALE'
--18. DISPLAY CITY WITH THE TOTAL NUMBER OF EMPLOYEES BELONGING TO EACH CITY.

SELECT CITY , COUNT(EID) AS CITY_TOTAL_EMPLOYEE
FROM EMPLOYEE
GROUP BY CITY
--19. COUNT NUMBER OF EMPLOYEES IN EACH CITY WHERE GENDER IS MALE.

SELECT CITY , COUNT(EID) AS MALE_EMPLOYEE_CITY
FROM EMPLOYEE
WHERE GENDER = 'MALE'
GROUP BY CITY
--20. DISPLAY MAXIMUM SALARY IN EACH DEPARTMENT WHERE CITY IS NOT AHMEDABAD.

SELECT DEPARTMENT , MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEE
WHERE CITY <> 'AHMEDABAD'
GROUP BY DEPARTMENT


--21. Display minimum salary in each city where gender is FEMALE. 

SELECT CITY , MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY CITY

--22. Give total salary of each department of EMPLOYEE table. 

SELECT DEPARTMENT , SUM(SALARY) 
FROM EMPLOYEE
GROUP BY DEPARTMENT
--23. Give average salary of each department of EMPLOYEE table without displaying the respective 
--department name. 

SELECT AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT
--24. Count the number of employees for each department in every city. 

SELECT DEPARTMENT,CITY , COUNT(EID) 
FROM EMPLOYEE
GROUP BY DEPARTMENT,CITY


--25. Calculate the total salary distributed to male and female employees. 

SELECT GENDER,SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY GENDER




--26. Give city wise maximum and minimum salary of female employees. 

SELECT CITY , MAX(SALARY) AS MAX_SALARY , MIN(SALARY) AS MIN_SALARY 
FROM EMPLOYEE
WHERE GENDER = 'FEMALE'
GROUP BY CITY
--27. Calculate department, city, and gender wise average salary. 

SELECT DEPARTMENT , CITY , GENDER , AVG(SALARY) AS AVG_SALARY 
FROM EMPLOYEE
GROUP BY DEPARTMENT , CITY , GENDER 
--28. Display the difference between the highest and lowest salaries. Label the column DIFFERENCE. 

SELECT MAX(SALARY) - MIN(SALARY) AS _DIFFERENCE
FROM EMPLOYEE
--29. Display sum of salaries of department wise where department name consist 5 letter.

SELECT DEPARTMENT , SUM(SALARY) AS SALARY
FROM EMPLOYEE
WHERE DEPARTMENT LIKE '_____'
GROUP BY DEPARTMENT


--30. Find the Maximum salary department & city wise in which city name starts with ‘R’. 

SELECT DEPARTMENT , CITY , MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEE
WHERE CITY LIKE 'R%'
GROUP BY DEPARTMENT , CITY


SELECT * FROM LIBRARYBORROWING


--I. DISPLAY THE TOTAL FINE AMOUNT COLLECTED FOR EACH BOOK GENRE. 

SELECT BOOKGENRE,SUM(FINEAMOUNT) 
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE

--II. FIND THE AVERAGE NUMBER OF DAYS BORROWED FOR EACH BOOK 
--GENRE. 

SELECT BOOKGENRE,AVG(DAYSBORROWED) AS  DAYBORROWED_AVG
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE
--III. DISPLAY THE NUMBER OF BORROWING RECORDS FOR EACH MEMBER.

SELECT MEMBERNAME , COUNT(BORROWID) AS BORROW_ID
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--IV. FIND THE MAXIMUM FINE AMOUNT PAID IN EACH BOOK GENRE.

SELECT BOOKGENRE , MAX(FINEAMOUNT) AS BOOKGENRE
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE
--V. DISPLAY THE MINIMUM DAYS BORROWED FOR EACH BOOK GENRE. 

SELECT BOOKGENRE , MIN(DAYSBORROWED) AS BOOKGENRE
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE


--VI. 
--FIND THE TOTAL NUMBER OF DAYS BOOKS WERE BORROWED BY EACH 
--MEMBER. 

SELECT MEMBERNAME , SUM(DAYSBORROWED) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--VII. DISPLAY THE AVERAGE FINE AMOUNT PAID BY EACH MEMBER. 
 
 SELECT MEMBERNAME, AVG(FINEAMOUNT) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--VIII. FIND THE HIGHEST NUMBER OF DAYS BORROWED BY EACH MEMBER.

SELECT MEMBERNAME , MAX(DAYSBORROWED) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--IX. FIND THE DIFFERENCE BETWEEN THE HIGHEST AND LOWEST FINE FOR 
--EACH GENRE.

SELECT BOOKGENRE ,  MAX(FINEAMOUNT) -  MIN(FINEAMOUNT)AS BOOKGENRE
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE
--X. FIND HOW MANY TIMES HAS EACH MEMBER BORROWED A BOOK.

SELECT MEMBERNAME , COUNT(DAYSBORROWED) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME



 
