CREATE TABLE LIBRARYBORROWING ( 
BORROWID INT PRIMARY KEY, 
MEMBERNAME VARCHAR (50), 
BOOKGENRE VARCHAR (30), 
DAYSBORROWED INT, 
FINEAMOUNT DECIMAL (8,2) 
);



INSERT INTO LIBRARYBORROWING VALUES 
(1, 'AMIT', 'FICTION', 12, 60.00), 
(2, 'NEHA', 'SCIENCE', 8, 20.00), 
(3, 'RAHUL', 'HISTORY', 15, 75.00), 
(4, 'PRIYA', 'FICTION', 5, 0.00), 
(5, 'KARAN', 'SCIENCE', 10, 35.00), 
(6, 'SNEHA', 'TECHNOLOGY', 20, 120.00), 
(7, 'AMIT', 'HISTORY', 7, 15.00), 
(8, 'NEHA', 'TECHNOLOGY', 18, 95.00), 
(9, 'RAHUL', 'FICTION', 9, 30.00), 
(10, 'PRIYA', 'SCIENCE', 11, 45.00)



SELECT * FROM LIBRARYBORROWING



SELECT * FROM LIBRARYBORROWING


--I. DISPLAY THE TOTAL FINE AMOUNT COLLECTED FOR EACH BOOK GENRE. 

SELECT BOOKGENRE,SUM(FINEAMOUNT) 
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE

--II. FIND THE AVERAGE NUMBER OF DAYS BORROWED FOR EACH BOOK 
--GENRE. 

SELECT BOOKGENRE,AVG(DAYSBORROWED) AS  DAYBORROWED_AVG
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE
--III. DISPLAY THE NUMBER OF BORROWING RECORDS FOR EACH MEMBER.

SELECT MEMBERNAME , COUNT(BORROWID) AS BORROW_ID
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--IV. FIND THE MAXIMUM FINE AMOUNT PAID IN EACH BOOK GENRE.

SELECT BOOKGENRE , MAX(FINEAMOUNT) AS BOOKGENRE
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE
--V. DISPLAY THE MINIMUM DAYS BORROWED FOR EACH BOOK GENRE. 

SELECT BOOKGENRE , MIN(DAYSBORROWED) AS BOOKGENRE
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE


--VI. 
--FIND THE TOTAL NUMBER OF DAYS BOOKS WERE BORROWED BY EACH 
--MEMBER. 

SELECT MEMBERNAME , SUM(DAYSBORROWED) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--VII. DISPLAY THE AVERAGE FINE AMOUNT PAID BY EACH MEMBER. 
 
 SELECT MEMBERNAME, AVG(FINEAMOUNT) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--VIII. FIND THE HIGHEST NUMBER OF DAYS BORROWED BY EACH MEMBER.

SELECT MEMBERNAME , MAX(DAYSBORROWED) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
--IX. FIND THE DIFFERENCE BETWEEN THE HIGHEST AND LOWEST FINE FOR 
--EACH GENRE.

SELECT BOOKGENRE ,  MAX(FINEAMOUNT) -  MIN(FINEAMOUNT)AS BOOKGENRE
FROM LIBRARYBORROWING
GROUP BY BOOKGENRE
--X. FIND HOW MANY TIMES HAS EACH MEMBER BORROWED A BOOK.

SELECT MEMBERNAME , COUNT(DAYSBORROWED) AS MEMBERNAME
FROM LIBRARYBORROWING
GROUP BY MEMBERNAME
