--PART – A: 
--1. CREATE A TABLE VALUED FUNCTION TO DISPLAY ALL STUDENT RECORDS.
CREATE OR ALTER FUNCTION STUDENT_REC()
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT

SELECT * FROM STUDENT_REC()
--2. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS ALL STUDENTS FROM THAT CITY. 

CREATE OR ALTER FUNCTION STUDENT_CITY(
	@CITY VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE CITY = @CITY

SELECT * FROM STUDENT_CITY('RAJKOT')
--3. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS ALL STUDENTS OF THAT BRANCH.


CREATE OR ALTER FUNCTION STUDENT_BRANCH(
	@BRANCH VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE BRANCH = @BRANCH

SELECT * FROM STUDENT_BRANCH('CIVIL')
--4. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS SPI AND RETURNS STUDENTS WHOSE SPI IS GREATER THAN ENTERED 
--SPI. 

CREATE OR ALTER FUNCTION STUDENT_BRANCH(
	@BRANCH VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE BRANCH = @BRANCH

SELECT * FROM STUDENT_BRANCH('CIVIL')
--5. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS MIN_SPI AND MAX_SPI AND RETURNS STUDENTS WHOSE SPI LIES 
--BETWEEN GIVEN RANGE. 


CREATE OR ALTER FUNCTION STUDENT_BRANCH(
	@MIN_SPI FLOAT,
	@MAX_SPI FLOAT
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE SPI BETWEEN @MIN_SPI AND @MAX_SPI

 SELECT * FROM STUDENT_BRANCH(7.00 , 9.00)

--PART – B:  
--6. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS STDID AND RETURNS DETAILS OF THAT STUDENT. 
CREATE OR ALTER FUNCTION STD_ID(
	@STDID INT
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE STDID = @STDID

SELECT * FROM STD_ID(101)
--7. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS STUDENTS WHOSE SPI IS GREATER THAN 7 FROM 
--THAT CITY. 

CREATE OR ALTER FUNCTION STD_CITY_WISE(
	@CITY VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE SPI > 7 AND CITY = @CITY
	

SELECT * FROM STD_CITY_WISE('RAJKOT')
--8. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS STUDENTS WHOSE SPI IS LESS THAN 8 FROM 
--THAT BRANCH. 

CREATE OR ALTER FUNCTION STD_BRANCH_WISE(
	@BRANCH VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE SPI < 8 AND BRANCH = @BRANCH
	

SELECT * FROM STD_BRANCH_WISE('COMPUTER')
--9. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS TOPN AND RETURNS TOP N STUDENTS BASED ON SPI.

CREATE OR ALTER FUNCTION STD_TOPN(
	@TOPN INT
)
RETURNS TABLE
AS
	RETURN SELECT TOP (@TOPN) * FROM STUDENT
	ORDER BY SPI DESC
	

SELECT * FROM STD_TOPN(3)
--10. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS HIGHEST SPI STUDENT FROM THAT BRANCH. 

CREATE OR ALTER FUNCTION STD_BRANCH_WISE_MAX(
	@BRANCH VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT TOP 1 * FROM STUDENT
	WHERE BRANCH = @BRANCH
	ORDER BY SPI DESC
	
	

SELECT * FROM STD_BRANCH_WISE_MAX('COMPUTER')
 
--PART – C:  
--11. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS TOTAL STUDENTS FROM THAT CITY.
_STU
CREATE OR ALTER FUNCTION CITY_WISE_TOTAL_STU(
	@CITY VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT COUNT(STDID) AS COUNT_ FROM STUDENT
	WHERE CITY = @CITY
	
	
	

SELECT * FROM CITY_WISE_TOTAL_STU('RAJKOT')
--12. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS STUDENTS ORDERED BY SPI IN DESCENDING 
--ORDER. 

CREATE OR ALTER FUNCTION BRANCH_WISE_DESC(
	@BRANCH VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM STUDENT
	WHERE BRANCH = @BRANCH
	
	


SELECT * FROM BRANCH_WISE_DESC('COMPUTER')
ORDER BY SPI DESC
--13. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS TOP 3 STUDENT FROM THAT CITY BASED ON SPI. 

--ORDER. 

CREATE OR ALTER FUNCTION CITY_TOP_3(
	@CITY VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT TOP 3 * FROM STUDENT
	WHERE CITY = @CITY
	
	


SELECT * FROM CITY_TOP_3('RAJKOT')
ORDER BY SPI DESC
--14. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS STDID AND RETURNS STUDENT RANK BASED ON SPI (RANK). 
CREATE OR ALTER FUNCTION STUDENT_RANK(
	@STDID INT
)
RETURNS TABLE
AS
	RETURN SELECT * FROM 
	(	
		SELECT STDID , SNAME , CITY , SPI , BRANCH , 
		RANK() OVER(ORDER BY SPI DESC) AS STUDENTRANK
		FROM STUDENT
	)
	AS S
	WHERE STDID = @STDID
	

SELECT * FROM STUDENT_RANK(101)


--15. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS STUDENTS HAVING SECOND HIGHEST SPI 
--FROM THAT BRANCH.

CREATE OR ALTER FUNCTION STUDENT_BRANCH(
	@BRANCH VARCHAR(30)
)
RETURNS TABLE
AS
	RETURN SELECT * FROM 
	(	
		SELECT STDID , SNAME , CITY , SPI , BRANCH , 
		DENSE_RANK() OVER(ORDER BY SPI DESC) AS STUDENTRANK
		FROM STUDENT
		WHERE BRANCH = @BRANCH
	)
	AS S
	WHERE STUDENTRANK = 2
	

SELECT * FROM STUDENT_BRANCH('COMPUTER')
