SELECT * FROM DEPARTMENT
SELECT * FROM PERSON




--PART – A: 
--1. COMBINE INFORMATION FROM PERSON AND DEPARTMENT TABLE USING CROSS JOIN OR CARTESIAN PRODUCT.

	SELECT * 
	FROM PERSON 
	CROSS JOIN DEPARTMENT
	
--2. FIND ALL PERSONS WITH THEIR DEPARTMENT NAME 

	SELECT P.PERSONID , P.PERSONNAME ,D.DEPARTMENTNAME
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID

--3. FIND ALL PERSONS WITH THEIR DEPARTMENT NAME & CODE. 
	
	SELECT P.PERSONNAME ,D.DEPARTMENTNAME , D.DEPARTMENTCODE
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	
--4. FIND ALL PERSONS WITH THEIR DEPARTMENT CODE AND LOCATION. 

	
	SELECT P.PERSONNAME ,D.LOCATION , D.DEPARTMENTCODE
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID


--5. FIND THE DETAIL OF THE PERSON WHO BELONGS TO MECHANICAL DEPARTMENT.
	
	SELECT P.PERSONNAME , D.DEPARTMENTNAME
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE D.DEPARTMENTNAME = 'MECHANICAL'

--6. FINAL PERSON’S NAME, DEPARTMENT CODE AND SALARY WHO LIVES IN AHMEDABAD CITY.

	SELECT P.PERSONNAME , D.DEPARTMENTCODE , P.SALARY
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE P.CITY = 'AHMEDABAD'
--7. FIND THE PERSON'S NAME WHOSE DEPARTMENT IS IN C-BLOCK.
	
	SELECT P.PERSONNAME , D.LOCATION
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE D.LOCATION = 'C-BLOCK'
--8. RETRIEVE PERSON NAME, SALARY & DEPARTMENT NAME WHO BELONGS TO JAMNAGAR CITY.

	SELECT P.PERSONNAME , P.SALARY , D.DEPARTMENTNAME , P.CITY
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE P.CITY = 'JAMNAGAR'
--9. RETRIEVE PERSON’S DETAIL WHO JOINED THE CIVIL DEPARTMENT AFTER 1-AUG-2001.

	SELECT P.PERSONNAME , P.SALARY , P.JOININGDATE , P.CITY , D.DEPARTMENTNAME
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE P.JOININGDATE > '2001/08/01' AND D.DEPARTMENTNAME = 'CIVIL'

--10. DISPLAY ALL THE PERSON'S NAME WITH THE DEPARTMENT WHOSE JOINING DATE DIFFERENCE WITH THE CURRENT DATE 
--IS MORE THAN 25 YEARS. 
	
	SELECT P.PERSONNAME , P.SALARY , P.JOININGDATE , P.CITY , D.DEPARTMENTNAME
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE DATEDIFF(YEAR , P.JOININGDATE , GETDATE()) > 25
	
--11. FIND DEPARTMENT WISE PERSON COUNTS.

	SELECT D.DEPARTMENTNAME, COUNT(P.PERSONID)
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	GROUP BY D.DEPARTMENTNAME


--12. GIVE DEPARTMENT WISE MAXIMUM & MINIMUM SALARY WITH DEPARTMENT NAME. 

	SELECT D.DEPARTMENTNAME, MAX(P.SALARY) AS MAX_SALARY , MIN(P.SALARY) AS MIN_SALARY
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	GROUP BY D.DEPARTMENTNAME
--13. FIND CITY WISE TOTAL, AVERAGE, MAXIMUM AND MINIMUM SALARY.

	SELECT P.CITY, 
	MAX(P.SALARY) AS MAX_SALARY , 
	MIN(P.SALARY) AS MIN_SALARY , 
	SUM(P.SALARY) AS TOTAL_SALARY,
	AVG(P.SALARY) AS AVG_SALARY
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	GROUP BY P.CITY
--14. FIND THE AVERAGE SALARY OF A PERSON WHO BELONGS TO AHMEDABAD CITY. 

	SELECT AVG(P.SALARY) AS AVG_SALARY
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE P.CITY = 'AHMEDABAD'
	
--15. PRODUCE OUTPUT LIKE: <PERSONNAME> LIVES IN <CITY> AND WORKS IN <DEPARTMENTNAME> DEPARTMENT. (IN 
--SINGLE COLUMN) 

	SELECT P.PERSONNAME + ' LIVES IN ' + P.CITY + ' AND WORKS IN ' + D.DEPARTMENTNAME + ' DEPARTMENT'
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID




--PART – B: 
--16. PRODUCE OUTPUT LIKE: <PERSONNAME> EARNS <SALARY> FROM <DEPARTMENTNAME> DEPARTMENT MONTHLY. (IN 
--SINGLE COLUMN) 

	SELECT P.PERSONNAME + ' EARNS ' + CAST(P.SALARY AS varchar(30)) + ' FROM ' + D.DEPARTMENTNAME + ' DEPARTMENT MONTHLY'
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
--17. FIND CITY & DEPARTMENT WISE TOTAL, AVERAGE & MAXIMUM SALARIES.

	SELECT D.DEPARTMENTNAME , P.CITY, SUM(P.SALARY) AS SUM_SALARY , AVG(P.SALARY) AS AVG_SALARY , MAX(P.SALARY) AS MAX_SALARY
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	GROUP BY D.DEPARTMENTNAME , P.CITY
	
--18. FIND ALL PERSONS WHO DO NOT BELONG TO ANY DEPARTMENT. 
	
	SELECT P.PERSONID , P.PERSONNAME , P.SALARY , P.CITY,D.*
	FROM PERSON P
	LEFT OUTER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE P.DEPARTMENTID IS NULL
	
--19. FIND ALL DEPARTMENTS WHOSE TOTAL SALARY IS EXCEEDING 100000. 
	
	SELECT D.DEPARTMENTNAME ,  SUM(P.SALARY) AS SUM_SALARY 
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	GROUP BY D.DEPARTMENTNAME
	HAVING SUM(P.SALARY) > 100000


--PART – C: 
--20. LIST ALL DEPARTMENTS WHO HAVE NO PERSON.
	
	SELECT D.DEPARTMENTNAME  
	FROM PERSON P
	RIGHT OUTER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE P.DEPARTMENTID IS NULL
	
--21. LIST OUT DEPARTMENT NAMES IN WHICH MORE THAN TWO PERSONS ARE WORKING.
	
	SELECT D.DEPARTMENTNAME  , COUNT(P.PERSONID) 
	FROM PERSON P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	GROUP BY D.DEPARTMENTNAME
	HAVING COUNT(P.PERSONID) > 2

--22. GIVE A 10% INCREMENT IN THE COMPUTER DEPARTMENT EMPLOYEE’S SALARY. (USE UPDATE)
	UPDATE  P
	SET P.SALARY = P.SALARY * 1.10
	FROM PERSON P INNER JOIN DEPARTMENT D 
	ON P.DEPARTMENTID = D.DEPARTMENTID
	WHERE D.DEPARTMENTNAME = 'COMPUTER';

	SELECT * FROM PERSON

	
	


	