SELECT * FROM STUDENT
SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT


--FROM THE TABLE STUDENT PERFORM THE FOLLOWING QUERIES:  
--PART – A: 


--1. DISPLAY THE DETAILS OF STUDENTS WHOSE SPI IS GREATER THAN THE AVERAGE SPI.
	
	SELECT * 
	FROM STUDENT 
	WHERE SPI > (
					SELECT AVG(SPI) FROM STUDENT
				)
	

--2. DISPLAY THE NAMES OF STUDENTS WHOSE SPI IS LESS THAN THE AVERAGE SPI.


	SELECT SNAME 
	FROM STUDENT 
	WHERE SPI < (
					SELECT AVG(SPI) FROM STUDENT
				)
--3. DISPLAY THE STUDENT DETAILS WHO HAS THE HIGHEST SPI.

	SELECT * 
	FROM STUDENT
	WHERE SPI = (
					SELECT MAX(SPI) FROM STUDENT
				)
--4. DISPLAY THE STUDENT DETAILS WHO HAS THE LOWEST SPI. 

	SELECT * 
	FROM STUDENT
	WHERE SPI = (
					SELECT MIN(SPI) FROM STUDENT
				)
--5. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN SPI OF STUDENT DHARMIK. 

	SELECT * 
	FROM STUDENT
	WHERE SPI > (
					SELECT SPI FROM STUDENT
					WHERE SNAME = 'DHARMIK'
				)
--6. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN SPI OF STUDENT RIYA.

	SELECT * 
	FROM STUDENT
	WHERE SPI < (
					SELECT SPI FROM STUDENT
					WHERE SNAME = 'RIYA'
				)
--7. DISPLAY THE STUDENTS WHO BELONG TO THE SAME BRANCH AS KRUNAL.

	SELECT * 
	FROM STUDENT
	WHERE BRANCH = (
					SELECT BRANCH FROM STUDENT
					WHERE SNAME = 'KRUNAL'
				)
--8. DISPLAY THE STUDENTS WHOSE BRANCH IS DIFFERENT FROM HETVI.
	
	SELECT *
	FROM STUDENT
	WHERE BRANCH != (
		SELECT BRANCH FROM STUDENT
		WHERE SNAME = 'HETVI'
	)
--9. DISPLAY THE SECOND HIGHEST SPI FROM RESULT TABLE.

	SELECT TOP 1 *
	FROM RESULT
	WHERE SPI < (
			SELECT MAX(SPI) FROM RESULT
		)
	ORDER BY SPI DESC
--10. DISPLAY THE SECOND LOWEST SPI FROM RESULT TABLE. 

	
	SELECT TOP 1 *
	FROM RESULT
	WHERE SPI > (
			SELECT MIN(SPI) FROM RESULT
		)
	ORDER BY SPI 
--11. DISPLAY THE NAMES OF STUDENTS WHOSE SPI IS ABOVE BRANCH-WISE AVERAGE SPI.

	SELECT * 
	FROM STUDENT S1
	WHERE SPI > (
			SELECT AVG(SPI) FROM STUDENT S2
			WHERE S1.BRANCH = S2.BRANCH
	)
--12. DISPLAY THE BRANCH HAVING MAXIMUM AVERAGE SPI.
	
	SELECT TOP 1 AVG(SPI) , BRANCH FROM STUDENT
	GROUP BY BRANCH
	ORDER BY AVG(SPI) DESC

--13. DISPLAY THE BRANCH HAVING MINIMUM AVERAGE SPI.

	SELECT TOP 1 AVG(SPI) , BRANCH FROM STUDENT
	GROUP BY BRANCH
	ORDER BY AVG(SPI) 
	
--FROM THE TABLE STUDENT_INFO AND RESULT PERFORM THE FOLLOWING QUERIES:  
--PART – B: 
--14. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN ALL STUDENTS OF ME BRANCH.

	SELECT  R.SPI,S.NAME
	FROM RESULT R
	JOIN STUDENT_INFO S
		
	ON S.RNO = R.RNO
	
	WHERE R.SPI > (
		SELECT MAX(SPI) FROM RESULT R
		JOIN STUDENT_INFO S
		
	ON S.RNO = R.RNO
		WHERE S.BRNACH = 'ME'
	)

--15. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN ANY STUDENT OF ME BRANCH.

SELECT  R.SPI,S.NAME
	FROM RESULT R
	JOIN STUDENT_INFO S
		
	ON S.RNO = R.RNO
	
	WHERE R.SPI < (
		SELECT MAX(SPI) FROM RESULT R
		JOIN STUDENT_INFO S
		
	ON S.RNO = R.RNO
		WHERE S.BRNACH = 'ME'
	)
--16. DISPLAY THE STUDENT DETAILS WHOSE SPI IS NOT EQUAL TO ANY SPI OF EC BRANCH STUDENTS.

	SELECT  R.SPI,S.NAME
	FROM RESULT R
	JOIN STUDENT_INFO S
	ON S.RNO = R.RNO
	WHERE R.SPI != (
		SELECT SPI FROM RESULT R
		JOIN STUDENT_INFO S	
		ON S.RNO = R.RNO
		WHERE S.BRNACH = 'EC'
	)
--17. DISPLAY THE NAMES OF STUDENTS WHO SCORED HIGHER SPI THAN STUDENT OF RNO 103.

	SELECT  R.SPI,S.NAME
	FROM RESULT R
	JOIN STUDENT_INFO S
	ON S.RNO = R.RNO
	WHERE R.SPI > (
		SELECT SPI FROM RESULT R
		JOIN STUDENT_INFO S	
		ON S.RNO = R.RNO
		WHERE S.RNO = 103
	)
--18. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN AVERAGE SPI OF THEIR OWN BRANCH.

	SELECT  R.SPI,S1.NAME,S1.BRNACH
	FROM RESULT R
	JOIN STUDENT_INFO S1
	ON S1.RNO = R.RNO
	WHERE R.SPI > (
		SELECT AVG(SPI) FROM RESULT R
		JOIN STUDENT_INFO S2
		ON S2.RNO = R.RNO
		WHERE S1.BRNACH = S2.BRNACH
	)
	
--19. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN THE AVERAGE SPI OF CE BRANCH BUT GREATER THAN THE 
--MAXIMUM SPI OF ME BRANCH.  

	SELECT  R.SPI,S.NAME,S.BRNACH
	FROM RESULT R
	JOIN STUDENT_INFO S
	ON S.RNO = R.RNO
	WHERE R.SPI > (
		SELECT AVG(SPI) FROM RESULT R
		JOIN STUDENT_INFO S
		ON S.RNO = R.RNO
		WHERE S.BRNACH = 'CE'
	)
	AND R.SPI > (
		SELECT MAX(SPI) FROM RESULT R
		JOIN STUDENT_INFO S
		ON S.RNO = R.RNO
		WHERE S.BRNACH = 'ME'
	)
--20. DISPLAY THE BRANCH NAMES WHOSE AVERAGE SPI IS GREATER THAN THE OVERALL AVERAGE SPI.
	SELECT  S.BRNACH
	FROM RESULT R
	JOIN STUDENT_INFO S
	ON S.RNO = R.RNO
	GROUP BY S.BRNACH
	HAVING AVG(R.SPI) > (
		SELECT AVG(R.SPI) FROM RESULT R
	)

	
--21. DISPLAY THE STUDENTS WHO HAVE MAXIMUM SPI IN THEIR RESPECTIVE BRANCH. 

	SELECT S1.BRNACH 
	FROM STUDENT_INFO S1
	INNER JOIN RESULT R
	ON R.RNO = S1.RNO
	WHERE SPI = (
		SELECT MAX(R.SPI) FROM RESULT R
		INNER JOIN STUDENT_INFO S2 
		ON S2.RNO = R.RNO
		WHERE S2.BRNACH = S1.BRNACH
	)
--22. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN THEIR AVERAGE SPI OF THEIR BRANCH AND GREATER THAN OVERALL 
--AVERAGE SPI.  
	
	SELECT * 
	FROM STUDENT_INFO S1
	INNER JOIN RESULT R
	ON R.RNO = S1.RNO
	WHERE R.SPI > (
		SELECT AVG(R.SPI) FROM RESULT R
		INNER JOIN STUDENT_INFO S2 
		ON S2.RNO = R.RNO
		WHERE S2.BRNACH = S1.BRNACH
	)
	AND R.SPI > (
		SELECT AVG(R.SPI) FROM RESULT R
	)

	
--PART – C: 
--23. DISPLAY THE STUDENTS WHOSE SPI IS GREATER THAN AT LEAST ONE STUDENT OF EVERY BRANCH.
	
	SELECT S1.BRNACH , S1.NAME , R.SPI
	FROM STUDENT_INFO S1
	INNER JOIN RESULT R
	ON R.RNO = S1.RNO
	WHERE R.SPI > ALL(
		SELECT MIN(R.SPI) FROM RESULT R
		INNER JOIN STUDENT_INFO S2 
		ON S2.RNO = R.RNO
		GROUP BY S2.BRNACH
	)

--24. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN ALL STUDENTS OF CE BRANCH.

	SELECT *
	FROM STUDENT_INFO S
	INNER JOIN RESULT R
	ON R.RNO = S.RNO
	WHERE R.SPI < ALL(
		SELECT R.SPI FROM RESULT R
		INNER JOIN STUDENT_INFO S1
		ON S1.RNO = R.RNO
		WHERE S1.BRNACH = 'CE'
	)
--25. DISPLAY THE BRANCH THAT CONTAINS THE STUDENT WITH HIGHEST SPI.
	
	SELECT *
	FROM STUDENT_INFO S
	INNER JOIN RESULT R
	ON R.RNO = S.RNO
	WHERE R.SPI >= ALL(
		SELECT MAX(R.SPI) FROM RESULT R
		INNER JOIN STUDENT_INFO S1
		ON S1.RNO = R.RNO
		GROUP BY S1.BRNACH
	)
--26. DISPLAY THE STUDENTS WHOSE SPI IS LESS THAN THE SPI OF EVERY STUDENT IN CE BRANCH AND GREATER THAN EVERY 
--STUDENT IN ME BRANCH.
SELECT *
FROM STUDENT_INFO S
INNER JOIN RESULT R
    ON R.RNO = S.RNO
WHERE R.SPI < ALL (
    SELECT R1.SPI
    FROM RESULT R1
    INNER JOIN STUDENT_INFO S1
        ON S1.RNO = R1.RNO
    WHERE S1.BRNACH = 'CE'
)
AND R.SPI > ALL (
    SELECT R2.SPI
    FROM RESULT R2
    INNER JOIN STUDENT_INFO S2
        ON S2.RNO = R2.RNO
    WHERE S2.BRNACH = 'ME'
);

SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT