--PART – A:
--1. HANDLE DIVIDE BY ZERO ERROR AND PRINT MESSAGE LIKE: ERROR OCCURS THAT IS - DIVIDE BY ZERO ERROR.
BEGIN TRY
    SELECT 10 / 0;
END TRY
BEGIN CATCH
    PRINT 'ERROR OCCURS THAT IS - DIVIDE BY ZERO ERROR.';
END CATCH;
--2. TRY TO CONVERT STRING TO INTEGER AND HANDLE THE ERROR USING TRY…CATCH BLOCK.
BEGIN TRY
    SELECT CAST('ABC' AS INT);
END TRY
BEGIN CATCH
    PRINT 'CONVERSION ERROR: CANNOT CONVERT STRING TO INTEGER.';
END CATCH;
--3. CREATE A PROCEDURE THAT PRINTS THE SUM OF TWO NUMBERS: TAKE BOTH NUMBERS AS INTEGER & HANDLE
--EXCEPTION WITH ALL ERROR FUNCTIONS IF ANY ONE ENTERS STRING VALUE IN NUMBERS OTHERWISE PRINT RESULT.

CREATE PROCEDURE PR_SUMTWONUMBERS
    @NUM1 VARCHAR(50),
    @NUM2 VARCHAR(50)
AS
BEGIN
    BEGIN TRY
        DECLARE @N1 INT = CAST(@NUM1 AS INT);
        DECLARE @N2 INT = CAST(@NUM2 AS INT);
        PRINT 'SUM: ' + CAST((@N1 + @N2) AS VARCHAR);
    END TRY
    BEGIN CATCH
        PRINT 'ERROR NUMBER: ' + CAST(ERROR_NUMBER() AS VARCHAR);
        PRINT 'ERROR SEVERITY: ' + CAST(ERROR_SEVERITY() AS VARCHAR);
        PRINT 'ERROR STATE: ' + CAST(ERROR_STATE() AS VARCHAR);
        PRINT 'ERROR MESSAGE: ' + ERROR_MESSAGE();
    END CATCH;
END;

--4. HANDLE A PRIMARY KEY VIOLATION WHILE INSERTING DATA INTO STUDENT_INFO TABLE AND PRINT THE ERROR
--DETAILS SUCH AS THE ERROR MESSAGE, ERROR NUMBER, SEVERITY, AND STATE.
BEGIN TRY
    INSERT INTO STUDENT_INFO (RNO, NAME, BRANCH)
    VALUES (101, 'DUPLICATE RAJU', 'CE'); -- 101 ALREADY EXISTS
END TRY
BEGIN CATCH
    PRINT 'ERROR NUMBER: ' + CAST(ERROR_NUMBER() AS VARCHAR);
    PRINT 'ERROR SEVERITY: ' + CAST(ERROR_SEVERITY() AS VARCHAR);
    PRINT 'ERROR STATE: ' + CAST(ERROR_STATE() AS VARCHAR);
    PRINT 'ERROR MESSAGE: ' + ERROR_MESSAGE();
END CATCH;
--5. THROW CUSTOM EXCEPTION USING STORED PROCEDURE WHICH ACCEPTS RNO AS INPUT & THAT THROWS ERROR LIKE
--NO RNO IS AVAILABLE IN DATABASE.
CREATE PROCEDURE PR_CHECKSTUDENTRNO
    @RNO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM STUDENT_INFO WHERE RNO = @RNO)
    BEGIN
        THROW 50001, 'NO RNO IS AVAILABLE IN DATABASE.', 1;
    END
    ELSE
    BEGIN
        SELECT * FROM STUDENT_INFO WHERE RNO = @RNO;
    END
END;
--PART – B
--6. CREATE A STORED PROCEDURE TO UPDATE EMPLOYEE SALARY AND THROW CUSTOM EXCEPTION IF SALARY IS
--NEGATIVE OR ZERO (USE EMPLOYEE TABLE).
CREATE PROCEDURE PR_UPDATEEMPLOYEESALARY
    @EID INT,
    @SALARY DECIMAL(8,2)
AS
BEGIN
    IF @SALARY <= 0
    BEGIN
        THROW 50002, 'SALARY MUST BE GREATER THAN ZERO.', 1;
    END
    
    UPDATE EMPLOYEE
    SET SALARY = @SALARY
    WHERE EID = @EID;
END;
--7. HANDLE A FOREIGN KEY VIOLATION WHILE INSERTING DATA INTO RESULT TABLE AND PRINT APPROPRIATE ERROR
--MESSAGE (USE RESULT TABLE).
BEGIN TRY
    INSERT INTO RESULT (RESULTID, SPI, RNO)
    VALUES (17, 8.5, 999); -- RNO 999 DOES NOT EXIST IN STUDENT_INFO
END TRY
BEGIN CATCH
    PRINT 'FOREIGN KEY VIOLATION ERROR: ' + ERROR_MESSAGE();
END CATCH;
--8. HANDLE INVALID DATE FORMAT WHILE INSERTING DATA INTO DEPOSIT TABLE.
BEGIN TRY
    INSERT INTO DEPOSIT (ACTNO, CNAME, BNAME, AMOUNT, ADATE)
    VALUES (120, 'TEST', 'MAVDI', 5000, 'INVALID-DATE-STRING');
END TRY
BEGIN CATCH
    PRINT 'INVALID DATE FORMAT ERROR: ' + ERROR_MESSAGE();
END CATCH;
--9. CREATE A STORED PROCEDURE THAT VALIDATES GENDER COLUMN AND THROWS ERROR IF VALUE IS OTHER THAN MALE OR
--FEMALE (USE EMPLOYEE TABLE).
CREATE PROCEDURE PR_VALIDATEGENDER
    @EID INT,
    @GENDER VARCHAR(10)
AS
BEGIN
    IF UPPER(@GENDER) NOT IN ('MALE', 'FEMALE')
    BEGIN
        THROW 50003, 'INVALID GENDER. ALLOWED VALUES ARE MALE OR FEMALE.', 1;
    END
    
    UPDATE EMPLOYEE
    SET GENDER = @GENDER
    WHERE EID = @EID;
END;
--10. CREATE A STORED PROCEDURE THAT ACCEPTS JOININGYEAR AND THROWS CUSTOM EXCEPTION IF ENTERED YEAR IS
--GREATER THAN CURRENT YEAR (USE EMPLOYEE TABLE).
CREATE PROCEDURE PR_VALIDATEJOININGYEAR
    @EID INT,
    @JOININGYEAR INT
AS
BEGIN
    IF @JOININGYEAR > YEAR(GETDATE())
    BEGIN
        THROW 50004, 'JOINING YEAR CANNOT BE GREATER THAN CURRENT YEAR.', 1;
    END
    
    UPDATE EMPLOYEE
    SET JOININGYEAR = @JOININGYEAR
    WHERE EID = @EID;
END;
--PART – C
--10. CREATE A STORED PROCEDURE TO DELETE EMPLOYEE RECORD AND HANDLE EXCEPTION IF EMPLOYEE DOES NOT EXIST.
CREATE PROCEDURE PR_DELETEEMPLOYEE
    @EID INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM EMPLOYEE WHERE EID = @EID)
    BEGIN
        THROW 50005, 'EMPLOYEE RECORD DOES NOT EXIST.', 1;
    END
    
    DELETE FROM EMPLOYEE WHERE EID = @EID;
END;
--11. CREATE A STORED PROCEDURE THAT THROWS CUSTOM EXCEPTION IF DEPARTMENT NAME IS NULL DURING INSERTION. 
CREATE PROCEDURE PR_INSERTEMPLOYEE
    @EID INT,
    @FIRSTNAME VARCHAR(50),
    @LASTNAME VARCHAR(50),
    @DEPARTMENT VARCHAR(50),
    @SALARY DECIMAL(8,2),
    @CITY VARCHAR(50),
    @GENDER VARCHAR(10),
    @JOININGYEAR INT
AS
BEGIN
    IF @DEPARTMENT IS NULL OR LTRIM(RTRIM(@DEPARTMENT)) = ''
    BEGIN
        THROW 50006, 'DEPARTMENT NAME CANNOT BE NULL OR EMPTY.', 1;
    END

    INSERT INTO EMPLOYEE (EID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, CITY, GENDER, JOININGYEAR)
    VALUES (@EID, @FIRSTNAME, @LASTNAME, @DEPARTMENT, @SALARY, @CITY, @GENDER, @JOININGYEAR);
END;