--FROM THE TABLE EMPLOYEE PERFORM THE FOLLOWING QUERIES:  

SELECT * FROM EMPLOYEE

--PART – A: 
--1. CREATE A CURSOR EMPLOYEE_CURSOR TO FETCH ALL ROWS FROM EMPLOYEE TABLE AND DISPLAY THEM.
	DECLARE @EID INT
	DECLARE DISPLAY_EMP CURSOR

	FOR 
		SELECT EID FROM EMPLOYEE

	OPEN DISPLAY_EMP
	FETCH NEXT FROM DISPLAY_EMP INTO @EID

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT * FROM EMPLOYEE
		WHERE EID = @EID
		FETCH NEXT FROM DISPLAY_EMP INTO @EID
	END

	CLOSE DISPLAY_EMP

	DEALLOCATE DISPLAY_EMP

	
--2. CREATE A CURSOR TO DISPLAY ALL FEMALE EMPLOYEES FROM EMPLOYEE TABLE.

	DECLARE @EID1 INT
	DECLARE DISPLAY_EMP_FEMALE CURSOR

	FOR 
		SELECT EID  FROM EMPLOYEE

	OPEN DISPLAY_EMP_FEMALE
	FETCH NEXT FROM DISPLAY_EMP_FEMALE INTO @EID1

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT * FROM EMPLOYEE
		WHERE EID = @EID1 AND GENDER = 'FEMALE'

		FETCH NEXT FROM DISPLAY_EMP_FEMALE INTO @EID1
	END

	CLOSE DISPLAY_EMP_FEMALE

	DEALLOCATE DISPLAY_EMP_FEMALE
--3. CREATE A CURSOR EMPLOYEE_CURSOR_FETCH TO FETCH RECORDS IN FORM OF EID_FIRSTNAME_LASTNAME. 
--(EXAMPLE: 101_HETVI_PATEL)

	DECLARE @EID2 INT , @FIRSTNAME VARCHAR(10) , @LASTNAME VARCHAR(10)
	DECLARE DISPLAY_EMP_FULLNAME CURSOR

	FOR 
		SELECT EID , FIRSTNAME , LASTNAME FROM EMPLOYEE

	OPEN DISPLAY_EMP_FULLNAME
	FETCH NEXT FROM DISPLAY_EMP_FULLNAME INTO @EID2 , @FIRSTNAME , @LASTNAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		PRINT CAST(@EID2 AS VARCHAR(10)) +  '_' + @FIRSTNAME + '_' + @LASTNAME;
			
		FETCH NEXT FROM DISPLAY_EMP_FULLNAME INTO @EID2 , @FIRSTNAME , @LASTNAME
	END

	CLOSE DISPLAY_EMP_FULLNAME

	DEALLOCATE DISPLAY_EMP_FULLNAME   
--4. CREATE A CURSOR TO FIND AND DISPLAY ALL EMPLOYEES WITH SALARY GREATER THAN 12000.

	DECLARE @SALARY DECIMAL(7,2) 
	DECLARE DISPLAY_EMP_SALARY CURSOR

	FOR 
		SELECT SALARY FROM EMPLOYEE
		WHERE SALARY > 12000

	OPEN DISPLAY_EMP_SALARY
	FETCH NEXT FROM DISPLAY_EMP_SALARY INTO @SALARY

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		SELECT * FROM EMPLOYEE
		WHERE SALARY = @SALARY
			
		FETCH NEXT FROM DISPLAY_EMP_SALARY INTO @SALARY
	END

	CLOSE DISPLAY_EMP_SALARY

	DEALLOCATE DISPLAY_EMP_SALARY
--5. CREATE A CURSOR TO DISPLAY ALL EMPLOYEES WHO JOINED IN YEAR 2022 OR LATER.

DECLARE @EID4 INT  
	DECLARE DISPLAY_EMP_YEAR CURSOR

	FOR 
		SELECT EID FROM EMPLOYEE
		WHERE JOININGYEAR >= 2022

	OPEN DISPLAY_EMP_YEAR
	FETCH NEXT FROM DISPLAY_EMP_YEAR INTO @EID4

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		SELECT * FROM EMPLOYEE
		WHERE EID = @EID4
			
		FETCH NEXT FROM DISPLAY_EMP_YEAR INTO @EID4
	END

	CLOSE DISPLAY_EMP_YEAR

	DEALLOCATE DISPLAY_EMP_YEAR
--6. CREATE A CURSOR TO FETCH EMPLOYEE NAME WITH DEPARTMENT NAME.

	DECLARE   @FIRSTNAME1 VARCHAR(10) , @LASTNAME2 VARCHAR(20) ,@DEPARTMENT VARCHAR(10)  
	DECLARE DISPLAY_EMP_PRINT_DEPA CURSOR

	FOR 
		SELECT  FIRSTNAME , LASTNAME , DEPARTMENT FROM EMPLOYEE

	OPEN DISPLAY_EMP_PRINT_DEPA
	FETCH NEXT FROM DISPLAY_EMP_PRINT_DEPA INTO  @FIRSTNAME1 , @LASTNAME2 ,@DEPARTMENT

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		PRINT @FIRSTNAME1 + @LASTNAME2 + ' WORKS IN ' + @DEPARTMENT + ' DEPARTMENT '  
		
			
		FETCH NEXT FROM DISPLAY_EMP_PRINT_DEPA INTO @FIRSTNAME1 , @LASTNAME2 , @DEPARTMENT
	END

	CLOSE DISPLAY_EMP_PRINT_DEPA

	DEALLOCATE DISPLAY_EMP_PRINT_DEPA
--(EXAMPLE: RAJ MEHTA WORKS IN IT DEPARTMENT) 
--7. CREATE A CURSOR TO UPDATE CITY AS ‘AHMEDABAD’ FOR EMPLOYEES WHOSE CITY VALUE IS NULL.

	DECLARE @ID INT; 
	DECLARE @CITY VARCHAR(10); 
	DECLARE CITY_CHANGE CURSOR FOR 
		SELECT EID , CITY 
		FROM EMPLOYEE
		WHERE CITY IS NULL
	OPEN CITY_CHANGE; 
	FETCH NEXT FROM CITY_CHANGE 
	INTO @ID, @CITY; 
	WHILE @@FETCH_STATUS = 0 
		BEGIN 
			UPDATE EMPLOYEE 
			SET CITY = 'AHMEDABAD' 
			WHERE EID = @ID  
		FETCH NEXT FROM CITY_CHANGE 
		INTO @ID, @CITY; 
		END; 
	CLOSE CITY_CHANGE; 
	DEALLOCATE CITY_CHANGE;


	SELECT * FROM EMPLOYEE
--8. CREATE A CURSOR TO DISPLAY EMPLOYEE NAME WITH CITY NAME. 

DECLARE   @FIRSTNAME2 VARCHAR(10) , @LASTNAME3 VARCHAR(20) ,@CITY1 VARCHAR(10)  
	DECLARE DISPLAY_EMP_PRINT_CITY CURSOR

	FOR 
		SELECT  FIRSTNAME , LASTNAME , CITY FROM EMPLOYEE

	OPEN DISPLAY_EMP_PRINT_CITY
	FETCH NEXT FROM DISPLAY_EMP_PRINT_CITY INTO  @FIRSTNAME2 , @LASTNAME3 ,@CITY1

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		PRINT @FIRSTNAME2 +  @LASTNAME3 + ' LIVES IN ' + @CITY1 
		
			
		FETCH NEXT FROM DISPLAY_EMP_PRINT_CITY INTO @FIRSTNAME2 , @LASTNAME3 , @CITY1
	END

	CLOSE DISPLAY_EMP_PRINT_CITY

	DEALLOCATE DISPLAY_EMP_PRINT_CITY
--(EXAMPLE: DEEP PATEL LIVES IN RAJKOT) 
--9. CREATE A CURSOR TO DELETE EMPLOYEES WHOSE SALARY IS LESS THAN 5000.

	DECLARE  @EID6 INT ,@SALARY1 DECIMAL(7,2)  
	DECLARE DELETE_EMP CURSOR

	FOR 
		SELECT  EID , SALARY FROM EMPLOYEE
		WHERE SALARY < 5000

	OPEN DELETE_EMP
	FETCH NEXT FROM DELETE_EMP INTO @EID6 , @SALARY1

	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		DELETE FROM EMPLOYEE
		WHERE EID = @EID6
		
			
		FETCH NEXT FROM DELETE_EMP INTO @EID6 , @SALARY1
	END

	CLOSE DELETE_EMP

	DEALLOCATE DELETE_EMP

	SELECT * FROM EMPLOYEE
--10. CREATE A CURSOR TO DISPLAY EMPLOYEES DEPARTMENT-WISE. 
	DECLARE  @DEPARTMENT1 VARCHAR(10) 
	DECLARE DEPARTMENT_WISE CURSOR

	FOR 
		SELECT  DEPARTMENT FROM EMPLOYEE
		GROUP BY DEPARTMENT

	OPEN DEPARTMENT_WISE
	FETCH NEXT FROM DEPARTMENT_WISE INTO @DEPARTMENT1

	WHILE @@FETCH_STATUS = 0
	BEGIN	
		SELECT * FROM EMPLOYEE
		WHERE DEPARTMENT = @DEPARTMENT1
		FETCH NEXT FROM DEPARTMENT_WISE INTO @DEPARTMENT1
	END

	CLOSE DEPARTMENT_WISE

	DEALLOCATE DEPARTMENT_WISE
--PART – B: 
--11. CREATE A CURSOR TO COUNT TOTAL EMPLOYEES FROM EACH DEPARTMENT.


DECLARE @DEPT11 VARCHAR(50), @COUNT11 INT;

DECLARE DEPT_COUNT_CURSOR CURSOR FOR
SELECT DEPARTMENT, COUNT(*)
FROM EMPLOYEE
GROUP BY DEPARTMENT;

OPEN DEPT_COUNT_CURSOR;


FETCH NEXT FROM DEPT_COUNT_CURSOR
INTO @DEPT11, @COUNT11;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @DEPT11 AS DEPARTMENT, @COUNT11 AS TOTAL_EMPLOYEES;

    FETCH NEXT FROM DEPT_COUNT_CURSOR
    INTO @DEPT11, @COUNT11;
END;

CLOSE DEPT_COUNT_CURSOR;
DEALLOCATE DEPT_COUNT_CURSOR;
--12. CREATE A CURSOR TO DISPLAY EMPLOYEES WHOSE CITY STARTS WITH LETTER ‘R’. 

DECLARE @EID12 INT, @FNAME12 VARCHAR(50), @CITY12 VARCHAR(50);


DECLARE R_CITY_CURSOR CURSOR FOR
SELECT EID, FIRSTNAME, CITY
FROM EMPLOYEE
WHERE CITY LIKE 'R%';

OPEN R_CITY_CURSOR;


FETCH NEXT FROM R_CITY_CURSOR
INTO @EID12, @FNAME12, @CITY12;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @EID12 AS EID, @FNAME12 AS FIRSTNAME, @CITY12 AS CITY;

    FETCH NEXT FROM R_CITY_CURSOR
    INTO @EID12, @FNAME12, @CITY12;
END;

CLOSE R_CITY_CURSOR;
DEALLOCATE R_CITY_CURSOR;
--13. CREATE A CURSOR TO DISPLAY TOP 3 HIGHEST SALARY EMPLOYEES FROM EMPLOYEE TABLE.

DECLARE @EID13 INT, @FNAME13 VARCHAR(50), @SAL13 DECIMAL(10,2);

DECLARE TOP3_CURSOR CURSOR FOR
SELECT TOP 3 EID, FIRSTNAME, SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC;

OPEN TOP3_CURSOR;


FETCH NEXT FROM TOP3_CURSOR
INTO @EID13, @FNAME13, @SAL13;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @EID13 AS EID, @FNAME13 AS FIRSTNAME, @SAL13 AS SALARY;

    FETCH NEXT FROM TOP3_CURSOR
    INTO @EID13, @FNAME13, @SAL13;
END;

CLOSE TOP3_CURSOR;
DEALLOCATE TOP3_CURSOR;

--14. CREATE A CURSOR TO CALCULATE TOTAL SALARY DEPARTMENT-WISE. 
--(EXAMPLE: IT DEPARTMENT TOTAL SALARY = 33000) 

DECLARE @DEPT14 VARCHAR(50), @TOTAL14 DECIMAL(10,2);

DECLARE TOTAL_SALARY_CURSOR CURSOR FOR
SELECT DEPARTMENT, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPARTMENT;

OPEN TOTAL_SALARY_CURSOR;


FETCH NEXT FROM TOTAL_SALARY_CURSOR
INTO @DEPT14, @TOTAL14;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @DEPT14 AS DEPARTMENT, @TOTAL14 AS TOTAL_SALARY;

    FETCH NEXT FROM TOTAL_SALARY_CURSOR
    INTO @DEPT14, @TOTAL14;
END;

CLOSE TOTAL_SALARY_CURSOR;
DEALLOCATE TOTAL_SALARY_CURSOR;

--15. CREATE A CURSOR TO CALCULATE AVERAGE SALARY CITY-WISE.

DECLARE @CITY15 VARCHAR(50), @AVG15 DECIMAL(10,2);

DECLARE AVG_SALARY_CURSOR CURSOR FOR
SELECT CITY, AVG(SALARY)
FROM EMPLOYEE
WHERE CITY IS NOT NULL
GROUP BY CITY;

OPEN AVG_SALARY_CURSOR;


FETCH NEXT FROM AVG_SALARY_CURSOR
INTO @CITY15, @AVG15;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @CITY15 AS CITY, @AVG15 AS AVERAGE_SALARY;

    FETCH NEXT FROM AVG_SALARY_CURSOR
    INTO @CITY15, @AVG15;
END;

CLOSE AVG_SALARY_CURSOR;
DEALLOCATE AVG_SALARY_CURSOR;

--PART – C: 
--16. CREATE A CURSOR TO DISPLAY EMPLOYEE EXPERIENCE USING JOININGYEAR.


DECLARE @FNAME16 VARCHAR(50), @LNAME16 VARCHAR(50),
        @YEAR16 INT;

DECLARE EXPERIENCE_CURSOR CURSOR FOR
SELECT FIRSTNAME, LASTNAME, JOININGYEAR
FROM EMPLOYEE;

OPEN EXPERIENCE_CURSOR;


FETCH NEXT FROM EXPERIENCE_CURSOR
INTO @FNAME16, @LNAME16, @YEAR16;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @FNAME16 + ' ' + @LNAME16 +
          ' HAS EXPERIENCE = ' +
          CAST(YEAR(GETDATE()) - @YEAR16 AS VARCHAR) + ' YEARS';

    FETCH NEXT FROM EXPERIENCE_CURSOR
    INTO @FNAME16, @LNAME16, @YEAR16;
END;

CLOSE EXPERIENCE_CURSOR;
DEALLOCATE EXPERIENCE_CURSOR;
--(EXAMPLE: RAJ MEHTA HAS EXPERIENCE = 4 YEARS) 
--17. CREATE A CURSOR TO DISPLAY EMPLOYEE FULL NAME WITH ANNUAL SALARY.

DECLARE @FNAME17 VARCHAR(50), @LNAME17 VARCHAR(50),
        @SAL17 DECIMAL(10,2);

DECLARE ANNUAL_SALARY_CURSOR CURSOR FOR
SELECT FIRSTNAME, LASTNAME, SALARY
FROM EMPLOYEE;

OPEN ANNUAL_SALARY_CURSOR;



FETCH NEXT FROM ANNUAL_SALARY_CURSOR
INTO @FNAME17, @LNAME17, @SAL17;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @FNAME17 + ' ' + @LNAME17 +
          ' ANNUAL SALARY = ' +
          CAST(@SAL17 * 12 AS VARCHAR);

    FETCH NEXT FROM ANNUAL_SALARY_CURSOR
    INTO @FNAME17, @LNAME17, @SAL17;
END;

CLOSE ANNUAL_SALARY_CURSOR;
DEALLOCATE ANNUAL_SALARY_CURSOR;

--(EXAMPLE: HETVI PATEL ANNUAL SALARY = 144000) 
--18. CREATE A CURSOR TO CALCULATE TOTAL MALE AND FEMALE EMPLOYEES SEPARATELY. 

DECLARE @GENDER18 VARCHAR(10), @COUNT18 INT;

DECLARE GENDER_CURSOR CURSOR FOR
SELECT GENDER, COUNT(*)
FROM EMPLOYEE
GROUP BY GENDER;

OPEN GENDER_CURSOR;


FETCH NEXT FROM GENDER_CURSOR
INTO @GENDER18, @COUNT18;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @GENDER18 AS GENDER, @COUNT18 AS TOTAL_EMPLOYEES;

    FETCH NEXT FROM GENDER_CURSOR
    INTO @GENDER18, @COUNT18;
END;

CLOSE GENDER_CURSOR;
DEALLOCATE GENDER_CURSOR;
--19. CREATE A CURSOR TO DISPLAY EMPLOYEES WHOSE SALARY IS GREATER THAN DEPARTMENT AVERAGE SALARY. 

DECLARE @EID19 INT, @FNAME19 VARCHAR(50), @LNAME19 VARCHAR(50),
        @SAL19 DECIMAL(10,2), @DEPT19 VARCHAR(50);

DECLARE ABOVE_AVG_CURSOR CURSOR FOR
SELECT E.EID, E.FIRSTNAME, E.LASTNAME, E.SALARY, E.DEPARTMENT
FROM EMPLOYEE E
WHERE E.SALARY >
(
    SELECT AVG(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPARTMENT = E.DEPARTMENT
);

OPEN ABOVE_AVG_CURSOR;


FETCH NEXT FROM ABOVE_AVG_CURSOR
INTO @EID19, @FNAME19, @LNAME19, @SAL19, @DEPT19;

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @EID19 AS EID, @FNAME19 AS FIRSTNAME,
           @LNAME19 AS LASTNAME, @SAL19 AS SALARY,
           @DEPT19 AS DEPARTMENT;

    FETCH NEXT FROM ABOVE_AVG_CURSOR
    INTO @EID19, @FNAME19, @LNAME19, @SAL19, @DEPT19;
END;

CLOSE ABOVE_AVG_CURSOR;
DEALLOCATE ABOVE_AVG_CURSOR;
--20. CREATE A CURSOR TO TRANSFER ALL EMPLOYEES FROM ADMIN DEPARTMENT TO HR DEPARTMENT. 

DECLARE @EID20 INT;

DECLARE ADMIN_CURSOR CURSOR FOR
SELECT EID
FROM EMPLOYEE
WHERE DEPARTMENT = 'ADMIN';

OPEN ADMIN_CURSOR;


FETCH NEXT FROM ADMIN_CURSOR INTO @EID20;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE EMPLOYEE
    SET DEPARTMENT = 'HR'
    WHERE EID = @EID20;

    FETCH NEXT FROM ADMIN_CURSOR INTO @EID20;
END;

CLOSE ADMIN_CURSOR;
DEALLOCATE ADMIN_CURSOR;