SELECT * FROM PUBLISHER
SELECT * FROM AUTHOR
SELECT * FROM BOOK


--Part – A: 
--1. List all books with their authors.

SELECT BOOKID,TITLE,A.AUTHORNAME,PRICE 
FROM BOOK B
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID

--2. List all books with their publishers.

SELECT BOOKID,TITLE,P.PUBLISHERNAME,PRICE 
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
--3. List all books with their authors and publishers.

SELECT BOOKID , TITLE , A.AUTHORNAME , P.PUBLISHERNAME 
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID

--4. List all books published after 2010 with their authors and publisher and price.


SELECT BOOKID , TITLE , A.AUTHORNAME , P.PUBLISHERNAME , B.PUBLICATIONYEAR
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
WHERE B.PUBLICATIONYEAR > 2010
--5. List all authors and the number of books they have written.

SELECT A.AUTHORNAME , COUNT(B.BOOKID) AS COUNT_BOOK
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY A.AUTHORNAME
--6. List all publishers and the total price of books they have published.
SELECT P.PUBLISHERNAME , SUM(B.PRICE) AS TOTAL
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY P.PUBLISHERNAME

--7. List authors who have not written any books.

SELECT A.AUTHORNAME
FROM BOOK B
RIGHT OUTER JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
WHERE B.BOOKID IS NULL


--8. Display the total number of books written by each author along with the average price of their books. 

SELECT A.AUTHORNAME, COUNT(B.BOOKID) AS COUNT_BOOK , AVG(B.PRICE) AS AVG_PRICE
FROM BOOK B
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME

--9. lists each publisher along with the total number of books they have published, sorted from highest to 
--lowest. 

SELECT A.PUBLISHERNAME, COUNT(B.BOOKID) AS COUNT_BOOK
FROM BOOK B
INNER JOIN PUBLISHER A
ON A.PUBLISHERID = B.PUBLISHERID
GROUP BY A.PUBLISHERNAME
ORDER BY COUNT(B.BOOKID) DESC

--10. Display number of books published each year. 

SELECT B.PUBLICATIONYEAR , COUNT(B.BOOKID)
FROM BOOK B
INNER JOIN PUBLISHER A
ON A.PUBLISHERID = B.PUBLISHERID
GROUP BY B.PUBLICATIONYEAR




--11. List the publishers whose total book prices exceed 500, ordered by the total price. 


SELECT P.PUBLISHERNAME, SUM(B.PRICE) AS COUNT_BOOK
FROM BOOK B
INNER JOIN PUBLISHER P
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME
HAVING SUM(B.PRICE) > 500
--12. List most expensive book for each author, sort it with the highest price.

SELECT A.AUTHORNAME , MAX(B.PRICE) AS MAX_PRICE
FROM BOOK B
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
ORDER BY MAX(B.PRICE) DESC

--13. Display publisher name and difference between maximum and minimum book price.

SELECT P.PUBLISHERNAME , MAX(B.PRICE) - MIN(B.PRICE) AS DIFF
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY P.PUBLISHERNAME
--14. List publisher name and total price of books published each year.

SELECT B.PUBLICATIONYEAR , P.PUBLISHERNAME ,SUM(B.PRICE) AS TOTAL 
FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY B.PUBLICATIONYEAR , P.PUBLISHERNAME

--15. Display author name and total price of books sorted by highest total price.

SELECT A.AUTHORNAME , SUM(B.PRICE) AS SUM_PRICE
FROM BOOK B
INNER JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
ORDER BY SUM(B.PRICE) DESC
