CREATE TABLE EMPLOYEE_MASTER
(	
	EMPLOYEENO VARCHAR(10),
	NAME VARCHAR(20),
	MANAGERNO VARCHAR(10)
)

INSERT INTO EMPLOYEE_MASTER
VALUES ('E01' , 'TARUN' , NULL),
	   ('E02' , 'ROHAN' , 'E02'),
	   ('E03' , 'PRIYA' , 'E01'),
	   ('E04' , 'MILAN' , 'E03'),
	   ('E05' , 'JAY' , 'E01'),
	   ('E06' , 'ANJANA' , 'E04')

SELECT * FROM EMPLOYEE_MASTER






--16. Retrieve the names of employee along with their manager’s name from the Employee table.

	SELECT E.NAME AS EMP , M.NAME AS MNG
	FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
	ON E.MANAGERNO = M.EMPLOYEENO

--17. Display employees who are managers.

	SELECT DISTINCT M.NAME 
	FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
	ON E.MANAGERNO = M.EMPLOYEENO
	
--18. Display number of employees working under each manager.

	SELECT  COUNT(E.EMPLOYEENO) , M.NAME
	FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
	ON E.MANAGERNO = M.EMPLOYEENO
	GROUP BY M.NAME
--19. Display the employee’s name along with their manager’s name and senior manager name. 

	SELECT E.NAME AS EMP , M.NAME AS MNG , SM.NAME SENIOR
	FROM EMPLOYEE_MASTER E 
	INNER JOIN EMPLOYEE_MASTER M
	ON E.MANAGERNO = M.EMPLOYEENO
	INNER JOIN EMPLOYEE_MASTER SM
	ON M.MANAGERNO = SM.EMPLOYEENO
	
	
--20. Display managers and count of employees under them in descending order.  
	
	SELECT  COUNT(E.EMPLOYEENO) , M.NAME
	FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
	ON E.MANAGERNO = M.EMPLOYEENO
	GROUP BY M.NAME
	ORDER BY COUNT(E.EMPLOYEENO) DESC