SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT


--PART – A: 
--1. COMBINE INFORMATION FROM STUDENT AND RESULT TABLE USING CROSS JOIN (CARTESIAN PRODUCT).

SELECT STUDENT_INFO.RNO , STUDENT_INFO.NAME , STUDENT_INFO.BRNACH 
FROM STUDENT_INFO CROSS JOIN RESULT

--2. PERFORM INNER JOIN ON STUDENT AND RESULT TABLES. 

SELECT S.RNO , S.NAME , S.BRNACH
FROM STUDENT_INFO S INNER JOIN RESULT R
ON S.RNO = R.RNO;
--3. PERFORM THE LEFT OUTER JOIN ON STUDENT AND RESULT TABLES.

SELECT S.RNO , S.NAME , S.BRNACH , R.RNO , R.SPI
FROM STUDENT_INFO S LEFT OUTER JOIN RESULT R
ON S.RNO = R.RNO;

--4. PERFORM THE RIGHT OUTER JOIN ON STUDENT AND RESULT TABLES.

SELECT S.RNO , S.NAME , S.BRNACH , R.RNO , R.SPI
FROM STUDENT_INFO S RIGHT OUTER JOIN RESULT R
ON S.RNO = R.RNO;
--5. PERFORM THE FULL OUTER JOIN ON STUDENT AND RESULT TABLES.

SELECT S.RNO , S.NAME , S.BRNACH , R.RNO , R.SPI
FROM STUDENT_INFO S FULL OUTER JOIN RESULT R
ON S.RNO = R.RNO;

--6. DISPLAY RNO, NAME, BRANCH AND SPI OF ALL STUDENTS.

SELECT S.RNO , S.NAME , S.BRNACH , R.SPI
FROM STUDENT_INFO S FULL OUTER JOIN RESULT R
ON S.RNO = R.RNO;
--7. DISPLAY RNO, NAME, BRANCH AND SPI OF CE BRANCH STUDENTS ONLY.

SELECT S.RNO , S.NAME , S.BRNACH , R.SPI
FROM STUDENT_INFO S FULL OUTER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE S.BRNACH = 'CE' 

--8. DISPLAY RNO, NAME, BRANCH AND SPI OF STUDENTS OTHER THAN EC BRANCH. 

SELECT S.RNO , S.NAME , S.BRNACH , R.SPI
FROM STUDENT_INFO S FULL OUTER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE S.BRNACH <> 'EC' 

--9. DISPLAY RNO, NAME AND SPI OF STUDENTS WHOSE SPI IS GREATER THAN 8.

SELECT S.RNO , S.NAME , R.SPI
FROM STUDENT_INFO S FULL OUTER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE R.SPI > 8 
--10. DISPLAY RNO, NAME AND BRANCH OF STUDENTS WHOSE SPI IS LESS THAN 8.

SELECT S.RNO , S.NAME , S.BRNACH
FROM STUDENT_INFO S FULL OUTER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE R.SPI < 8 
--11. DISPLAY AVERAGE RESULT OF EACH BRANCH.

SELECT S.BRNACH  , AVG(SPI) AS AVG_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH

--12. DISPLAY AVERAGE RESULT OF CE AND ME BRANCH. 


SELECT S.BRNACH  , AVG(SPI) AS AVG_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE S.BRNACH IN ('CE' , 'ME')
GROUP BY S.BRNACH
--13. DISPLAY MAXIMUM AND MINIMUM SPI OF EACH BRANCH.

SELECT S.BRNACH  , MAX(SPI) AS MAX_SPI , MIN(SPI) AS MIN_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH

--14. DISPLAY BRANCH-WISE STUDENT COUNT IN DESCENDING ORDER.

SELECT S.BRNACH  , COUNT(S.RNO) AS STUDENT
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
ORDER BY COUNT(S.RNO) DESC
--15. DISPLAY BRANCH-WISE TOTAL SPI OF STUDENTS.


SELECT S.BRNACH  , SUM(R.SPI) AS SUM_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH







--PART – B: 
--16. DISPLAY BRANCH-WISE NUMBER OF STUDENTS HAVING SPI GREATER THAN 8.

SELECT S.BRNACH  , COUNT(S.RNO) AS STUNDET
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE R.SPI > 8
GROUP BY S.BRNACH

--17. DISPLAY BRANCH-WISE NUMBER OF STUDENTS HAVING SPI LESS THAN 8. 


SELECT S.BRNACH  , COUNT(S.RNO) AS STUNDET
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
WHERE R.SPI < 8
GROUP BY S.BRNACH

--18. DISPLAY BRANCH-WISE AVERAGE SPI GREATER THAN 7.

SELECT S.BRNACH  , AVG(SPI) AS STUNDET_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
HAVING AVG(SPI) > 7
--19. DISPLAY BRANCHES HAVING MORE THAN 1 STUDENTS. 

SELECT S.BRNACH  , COUNT(S.RNO) AS STUDENT
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
HAVING COUNT(S.RNO) > 1
--20. DISPLAY BRANCHES WHERE MAXIMUM SPI IS GREATER THAN 9. 

SELECT S.BRNACH  , MAX(SPI) AS MAX_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
HAVING MAX(SPI) > 9




--PART – C: 
--21. DISPLAY AVERAGE RESULT OF EACH BRANCH AND SORT THEM IN ASCENDING ORDER BY SPI.

SELECT S.BRNACH  , AVG(SPI) AS AVG_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
ORDER BY AVG(SPI)
--22. DISPLAY HIGHEST SPI FROM EACH BRANCH AND SORT THEM IN DESCENDING ORDER.

SELECT S.BRNACH  , MAX(SPI) AS MAX_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
ORDER BY MAX(SPI) DESC
--23. DISPLAY AVERAGE RESULT OF EACH BRANCH AND SORT THEM IN ASCENDING ORDER BY SPI.

SELECT S.BRNACH  , AVG(SPI) AS AVG_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
ORDER BY AVG(SPI)

--24. DISPLAY HIGHEST SPI FROM EACH BRANCH AND SORT THEM IN DESCENDING ORDER.

SELECT S.BRNACH  , MAX(SPI) AS MAX_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
ORDER BY MAX(SPI) DESC
--25. DISPLAY BRANCHES WHERE DIFFERENCE BETWEEN MAX AND MIN SPI IS GREATER THAN 1.

SELECT S.BRNACH  , MAX(SPI) AS MAX_SPI , MIN(SPI) AS MIN_SPI
FROM STUDENT_INFO S INNER JOIN RESULT R 
ON S.RNO = R.RNO
GROUP BY S.BRNACH
HAVING MAX(SPI) - MIN(SPI) > 1
ORDER BY MAX(SPI) DESC