--PART – A:
--1. CREATE A STORED PROCEDURE TO GENERATE DEPARTMENT-WISE SALARY STATISTICS LIKE TOTAL SALARY, AVERAGE
--SALARY, MINIMUM SALARY, AND MAXIMUM SALARY. (USER ENTER ONLY DEPARTMENT NAME)

 CREATE OR ALTER PROCEDURE PR_MAX_MIN_AVG_TOTAL_SALARY
 @DEPARTMENT VARCHAR(30)
 AS
 BEGIN
		SELECT 
		SUM(SALARY) AS TOTAL_SALARY , 
		AVG(SALARY) AS AVG_SALARY , 
		MIN(SALARY)  AS MIN_SALARY ,
		MAX(SALARY) AS MAX_SALARY
		FROM EMPLOYEE
		WHERE DEPARTMENT = @DEPARTMENT
 END

 EXEC PR_MAX_MIN_AVG_TOTAL_SALARY 'IT'

 
--2. CREATE A STORED PROCEDURE THAT ACCEPTS A JOINING YEAR AND DISPLAYS EMPLOYEES WHO JOINED THAT YEAR.

 CREATE OR ALTER PROCEDURE PR_YEAR_EMP
	@JOININGYEAR INT
 AS
 BEGIN
		SELECT *
		FROM EMPLOYEE
		WHERE JOININGYEAR = @JOININGYEAR
 END
 EXEC PR_YEAR_EMP 2026

--3. CREATE A STORED PROCEDURE FOR DYNAMIC EMPLOYEE SEARCH USING PARAMETERS (USER MAY ENTER PARTIAL CITY
--NAME).

 CREATE OR ALTER PROCEDURE PR_CITY_EMP
	@CITY VARCHAR(30)
 AS
 BEGIN
	SELECT * FROM EMPLOYEE
	WHERE CITY LIKE '%'+@CITY+'%'
 END
 EXEC PR_CITY_EMP 'AHM'

--4. CREATE A STORED PROCEDURE THAT ACCEPTS A SALARY AMOUNT AND DISPLAYS EMPLOYEES EARNING MORE THAN THE
--ENTERED SALARY.

CREATE OR ALTER PROCEDURE PR_HIGHER_SALARY
	@SALARY DECIMAL(8,2)
AS
BEGIN 
	SELECT * FROM EMPLOYEE
	WHERE SALARY > @SALARY
END
EXEC PR_HIGHER_SALARY 12000.00
--5. CREATE A STORED PROCEDURE TO DISPLAY TOP N HIGHEST PAID EMPLOYEES FROM EACH DEPARTMENT (VALUE OF N
--IS ENTERED BY USER).
CREATE OR ALTER PROCEDURE PR_TOP_N_HIGEST_PAID_EMPLOYEE
	@N INT
AS
BEGIN
	SELECT * 
	FROM(
		SELECT * , ROW_NUMBER() OVER(PARTITION BY DEPARTMENT 
									 ORDER BY SALARY DESC) AS ORDER_RANK
		FROM EMPLOYEE
		) AS T
		WHERE ORDER_RANK <= @N 
END
EXEC PR_TOP_N_HIGEST_PAID_EMPLOYEE 2
--6. CREATE A STORED PROCEDURE TO INCREASE SALARY DEPARTMENT-WISE BY A GIVEN PERCENTAGE. (USER ENTER
--DEPARTMENT NAME AND %, E.G. COMPUTER 10).

CREATE OR ALTER PROCEDURE PR_INCREASE_SALARY
	@DNAME VARCHAR(30) ,
	@INCREMENT DECIMAL(5,2)
AS
BEGIN
	UPDATE EMPLOYEE
	SET SALARY = SALARY + (SALARY * @INCREMENT / 100)
	WHERE DEPARTMENT = @DNAME
END

EXEC PR_INCREASE_SALARY 'SERVER' , 10

SELECT * FROM EMPLOYEE

--7. CREATE A STORED PROCEDURE TO DISPLAY EMPLOYEES HAVING EXPERIENCE GREATER THAN OR EQUAL TO THE ENTERED
--YEARS.

CREATE OR ALTER PROCEDURE PR_EXPERIENCED_EMP
	@YEAR INT
AS 
BEGIN
	SELECT *
	FROM EMPLOYEE
	WHERE (YEAR(GETDATE()) - JOININGYEAR) >= @YEAR
END

EXEC PR_EXPERIENCED_EMP 3


--8. CREATE A STORED PROCEDURE THAT ACCEPTS A NUMBER AS INPUT AND DISPLAYS DETAILS OF THE LAST N EMPLOYEES
--WHO JOINED THE ORGANIZATION. 

CREATE OR ALTER PROCEDURE PR_LAST_N
	@N INT
AS 
BEGIN 
	SELECT TOP (@N)* FROM EMPLOYEE
	ORDER BY JOININGYEAR DESC
END

EXEC PR_LAST_N 3


--FROM THE TABLE AUTHOR, PUBLISHER AND BOOK PERFORM THE FOLLOWING QUERIES:

SELECT * FROM AUTHOR
SELECT * FROM PUBLISHER
SELECT * FROM BOOK
--PART – B:
--9. CREATE A STORED PROCEDURE THAT ACCEPTS AN AUTHOR NAME AND DISPLAYS ALL BOOKS WRITTEN BY THAT AUTHOR.

CREATE OR ALTER PROCEDURE PR_AUTHONNAME_BOOK
	@NAME VARCHAR(30)
AS
BEGIN
	SELECT A.AUTHORNAME , A.COUNTRY , B.TITLE 
	FROM AUTHOR A
	INNER JOIN BOOK B
	ON B.AUTHORID = A.AUTHORID
	WHERE A.AUTHORNAME = @NAME
END

EXEC PR_AUTHONNAME_BOOK 'CHETAN BHAGAT'
--10. CREATE A STORED PROCEDURE THAT ACCEPTS A PUBLICATION YEAR AND DISPLAYS BOOKS PUBLISHED AFTER THAT YEAR.

CREATE OR ALTER PROCEDURE PR_BOOK_TITLE
	@YEAR INT
AS
BEGIN
	SELECT TITLE , PUBLICATIONYEAR FROM BOOK
	WHERE PUBLICATIONYEAR > @YEAR
END

EXEC PR_BOOK_TITLE 2010
--11. CREATE A STORED PROCEDURE THAT ACCEPTS A COUNTRY NAME AND DISPLAYS ALL AUTHORS FROM THAT COUNTRY WITH
--THEIR BOOKS.

CREATE OR ALTER PROCEDURE PR_AUTHONNAME_BOOK
	@COUNTRY VARCHAR(30)
AS
BEGIN
	SELECT A.AUTHORNAME , A.COUNTRY , B.TITLE 
	FROM AUTHOR A
	INNER JOIN BOOK B
	ON B.AUTHORID = A.AUTHORID
	WHERE A.COUNTRY = @COUNTRY
END

EXEC PR_AUTHONNAME_BOOK 'INDIA'

--12. CREATE A STORED PROCEDURE THAT ACCEPTS A NUMBER AS INPUT AND DISPLAYS THE TOP N MOST EXPENSIVE BOOKS
--WITH AUTHOR AND PUBLISHER DETAILS.
CREATE OR ALTER PROCEDURE PR_EXPENSIVE_BOOK
	@N INT 
AS
BEGIN
	SELECT TOP (@N) A.AUTHORNAME , B.PRICE , P.PUBLISHERNAME
	FROM AUTHOR A
	INNER JOIN BOOK B
	ON A.AUTHORID = B.AUTHORID
	INNER JOIN PUBLISHER P
	ON P.PUBLISHERID = B.PUBLISHERID
	ORDER BY B.PRICE DESC
END

EXEC PR_EXPENSIVE_BOOK 3


--PART – C:
--13. CREATE A STORED PROCEDURE THAT ACCEPTS A PUBLISHER NAME AND DISPLAYS THE TOTAL NUMBER OF BOOKS
--PUBLISHED BY THAT PUBLISHER.
CREATE OR ALTER PROCEDURE PR_PUBLISHERNAME
	@NAME VARCHAR(30) , @COUNT INT OUTPUT
AS
BEGIN
	SELECT COUNT(B.BOOKID) AS TOTAL_BOOKS
	FROM BOOK B
	INNER JOIN PUBLISHER P
	ON P.PUBLISHERID = B.PUBLISHERID
	WHERE P.PUBLISHERNAME = @NAME
END

DECLARE @CNT INT 
EXEC PR_PUBLISHERNAME 'PENGUIN INDIA' , @COUNT = @CNT OUTPUT 
--SELECT @CNT

--14. CREATE A STORED PROCEDURE THAT ACCEPTS A PRICE RANGE (MIN PRICE MAX PRICE) AND DISPLAYS BOOKS WHOSE
--PRICES FALL WITHIN THAT RANGE.

CREATE OR ALTER PROCEDURE PR_BOOK_PRICE_RANGE
    @MIN_PRICE DECIMAL(10,2),
    @MAX_PRICE DECIMAL(10,2)
AS
BEGIN
    SELECT *
    FROM BOOK
    WHERE PRICE BETWEEN @MIN_PRICE AND @MAX_PRICE;
END;

EXEC PR_BOOK_PRICE_RANGE 200, 500;

--15. CREATE A STORED PROCEDURE THAT ACCEPTS AN AUTHOR ID AND DELETES ALL BOOKS WRITTEN BY THAT AUTHOR. 


CREATE OR ALTER PROCEDURE PR_DELETE_AUTHOR_BOOKS
    @AUTHOR_ID INT
AS
BEGIN
    DELETE FROM BOOK
    WHERE AUTHORID = @AUTHOR_ID;
END;

EXEC PR_DELETE_AUTHOR_BOOKS 2;

SELECT * FROM BOOK