SELECT * FROM STUDENT

--Part – A: 
--1. Display all students whose SPI is greater than 8. 

	WITH STUDENT_SPI AS
	(
		SELECT STDID , SNAME , CITY , SPI , BRANCH
		FROM STUDENT
		WHERE SPI > 8
	)
	SELECT * FROM STUDENT_SPI
--2. Display average SPI of all students.
	
	WITH STUDENT_AVG_SPI AS
	(
		SELECT AVG(SPI) AS AVG_SPI 
		FROM STUDENT
		
	)
	SELECT * FROM STUDENT_AVG_SPI
	
--3. Display total number of students in each branch.

	WITH STUDENT_TOTAL AS
	(
		SELECT BRANCH,COUNT(STDID) AS AVG_SPI 
		FROM STUDENT
		GROUP BY BRANCH
		
	)
	SELECT * FROM STUDENT_TOTAL
--4. Display students who belong to RAJKOT city.

	WITH STUDENT_CITY AS
	(
		SELECT * 
		FROM STUDENT
		WHERE CITY = 'RAJKOT' 
		
	)
	SELECT * FROM STUDENT_CITY
--5. Find branch names that appear more than once.

	WITH STUDENT_BRANCH AS
	(
		SELECT BRANCH , COUNT(BRANCH) AS NUMBER_OF_BRANCH
		FROM STUDENT
		GROUP BY BRANCH
		HAVING COUNT(BRANCH) > 1 
	)
	SELECT * FROM STUDENT_BRANCH
--6. Display row number for each student.

	WITH STUDENT_ROW_NUMBER AS
	(
		SELECT * , 
		ROW_NUMBER() OVER(ORDER BY SPI) AS ROW_NUMBER_SPI
		FROM STUDENT
	)
	SELECT * FROM STUDENT_ROW_NUMBER
--7. Display top 3 students based on SPI. 

	WITH STUDENT_TOP3 AS
	(
		SELECT * , 
		DENSE_RANK() OVER(ORDER BY SPI DESC) AS TOP_3_SPI
		FROM STUDENT
	)
	SELECT * FROM STUDENT_TOP3
	WHERE TOP_3_SPI <= 3
--8. Display students having maximum SPI. 
	WITH STUDENT_MAX AS
	(
		SELECT MAX(SPI) AS TOPPER 
		FROM STUDENT
	)
	SELECT * FROM STUDENT_MAX
	
--9. Display students having minimum SPI.
	WITH STUDENT_MIN AS
	(
		SELECT MIN(SPI) AS LOWER_ 
		FROM STUDENT
	)
	SELECT * FROM STUDENT_MIN
--10. Display branch -wise rank of students. 
	WITH STUDENT_BRANCH_WISE AS
	(
		SELECT * , 
		RANK() OVER(PARTITION BY BRANCH
		ORDER BY SPI DESC) AS BRANCH_WISE
		FROM STUDENT
	)
	SELECT * FROM STUDENT_BRANCH_WISE
	
--Part – B: 
--11. Display students SPI average belonging to Computer branch.
	WITH STUDENT_COMPUTER AS
	(
		SELECT BRANCH, AVG(SPI) AS COMPUTER_BRANCH 
		FROM STUDENT
		WHERE BRANCH = 'COMPUTER'
		GROUP BY BRANCH
	)
	SELECT * FROM STUDENT_COMPUTER
	
--12. Display students whose SPI is greater than average SPI of his/her branch.
	
	WITH SPI_AVG AS
	(
		SELECT BRANCH, AVG(SPI) AS AVG_SPI
		FROM STUDENT
		GROUP BY BRANCH
	)
	SELECT * 
	FROM SPI_AVG A
	INNER JOIN STUDENT S
	ON A.BRANCH = S.BRANCH
	WHERE A.AVG_SPI < S.SPI
	
--13. Display branch having more than 2 students.

	WITH STUDENT_BRANCH_STUDENT AS
	(
		SELECT BRANCH , COUNT(STDID) AS STUDENT_COUNT
		FROM STUDENT
		GROUP BY BRANCH
	)
	SELECT * FROM STUDENT_BRANCH_STUDENT
	WHERE STUDENT_COUNT > 2
--14. Display branches having average SPI between 7 and 9 
	WITH BRANCH_SPI_AVG AS
	(
		SELECT BRANCH, AVG(SPI) AS AVG_SPI
		FROM STUDENT
		GROUP BY BRANCH
	)
	SELECT * FROM BRANCH_SPI_AVG
	WHERE AVG_SPI BETWEEN 7 AND 9

--15. Display students whose SPI is lower than overall average SPI. 
	
	WITH SPI_AVG AS
	(
		SELECT AVG(SPI) AS AVG_SPI
		FROM STUDENT
	)
	SELECT * 
	FROM SPI_AVG A
	,STUDENT S
	WHERE A.AVG_SPI > S.SPI

--Part – C: 
--16. Display branches having exactly one student.

	WITH STUDENT_BRANCH_STUDENT AS
	(
		SELECT BRANCH , COUNT(STDID) AS STUDENT_COUNT
		FROM STUDENT
		GROUP BY BRANCH
	)
	SELECT * FROM STUDENT_BRANCH_STUDENT
	WHERE STUDENT_COUNT = 1
--17. Display branch having highest average SPI.

	WITH AVG_SPI AS
	(	
		SELECT BRANCH,AVG(SPI) AS AVG_SPI_STD
		FROM STUDENT
		GROUP BY BRANCH
	),
	MAX_AVG_SPI AS
	(
		SELECT MAX(AVG_SPI_STD) AS BRANCH_MAX_SPI
		FROM AVG_SPI
	)

	SELECT * FROM MAX_AVG_SPI
--18. Display branch having lowest average SPI.

	WITH BRANCH_AVG_SPI AS
	(	
		SELECT BRANCH,AVG(SPI) AS AVG_SPI_STD
		FROM STUDENT
		GROUP BY BRANCH
	),
	MIN_AVG_SPI AS
	(
		SELECT MIN(AVG_SPI_STD) AS MIN_SPI
		FROM BRANCH_AVG_SPI
	)

	SELECT * FROM MIN_AVG_SPI
--19. Display students whose SPI is lower than branch average SPI.
	WITH SPI_AVG AS
	(
		SELECT BRANCH, AVG(SPI) AS AVG_SPI
		FROM STUDENT
		GROUP BY BRANCH
	)
	SELECT * 
	FROM SPI_AVG A
	INNER JOIN STUDENT S
	ON A.BRANCH = S.BRANCH
	WHERE A.AVG_SPI > S.SPI

--20. Display branches having maximum number of students.

	WITH STUDENT_BRANCH_STUDENT AS
	(
		SELECT BRANCH , COUNT(STDID) AS STUDENT_COUNT
		FROM STUDENT
		GROUP BY BRANCH
	),
	MAX_BRANCH_STU AS
	(
	  SELECT MAX(STUDENT_COUNT) AS MAX_COUNT FROM STUDENT_BRANCH_STUDENT
	)
	SELECT * FROM MAX_BRANCH_STU
	