--EMPLOYEE_LOG (LOGID, EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
	
 SELECT * FROM EMPLOYEE

--FROM THE TABLE EMPLOYEE PERFORM THE FOLLOWING QUERIES:  
--PART – A: 
--1. CREATE TRIGGER FOR PRINTING MESSAGE AFTER EMPLOYEE RECORD INSERTION. 
	
	CREATE OR ALTER TRIGGER TR_INSERT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		PRINT 'RECORD IS INSERTED'
	END

	 INSERT INTO EMPLOYEE
	 VALUES (116 , 'JENISH' , 'BUSA' , 'IT' , 15000 , 'RAJKOT' , 'MALE' , 2028)

--2. CREATE TRIGGER FOR PRINTING MESSAGE AFTER EMPLOYEE RECORD UPDATE.

	CREATE OR ALTER TRIGGER TR_UPDATE
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		PRINT 'RECORD IS UPDATED'
	END

	UPDATE EMPLOYEE
	SET DEPARTMENT = 'HR'
	WHERE EID = 112

	

	 
--3. CREATE TRIGGER FOR PRINTING MESSAGE AFTER EMPLOYEE RECORD DELETION.

	CREATE OR ALTER TRIGGER TR_DELETE
	ON EMPLOYEE
	AFTER DELETE
	AS
	BEGIN
		PRINT 'RECORD IS DELETED'
	END

	DELETE FROM EMPLOYEE
	WHERE EID = 116
--4. CREATE TRIGGER FOR PRINTING MESSAGE AFTER EMPLOYEE SALARY INCREMENT.

	CREATE OR ALTER TRIGGER TR_SALARY_INCREMENT
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		PRINT 'SALARY UPDATED'
	END

	UPDATE EMPLOYEE
	SET SALARY = 20000
	WHERE EID = 111
--5. CREATE TRIGGER FOR AUTOMATICALLY CONVERTING CITY NAMES INTO UPPERCASE DURING INSERTION.

	CREATE TRIGGER trg_UppercaseCity
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		UPDATE EMPLOYEE
		SET CITY = UPPER(E.City)
		FROM EMPLOYEE E
		INNER JOIN inserted i
		ON E.EID = i.EID;
	END;


	 INSERT INTO EMPLOYEE
	 VALUES (117 , 'JENISH' , 'BUSA' , 'IT' , 15000 , 'rajkot' , 'MALE' , 2028)

	
	 SELECT * FROM EMPLOYEE

 
--PART – B: 
--6. CREATE TRIGGER FOR UPDATING EMPLOYEE CITY AND PRINTING OLD CITY AND NEW CITY NAME. 

CREATE TRIGGER TR_PRINT_CITY
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		SELECT I.CITY AS NEW_CITY, D.CITY AS OLD_CITY
		FROM deleted D
		INNER JOIN inserted i
		ON D.EID = i.EID;
	END;

	UPDATE EMPLOYEE
	SET CITY = 'UTI'
	WHERE EID = 117


	

	
	 SELECT * FROM EMPLOYEE	
--7. CREATE TRIGGER FOR AUTOMATICALLY SETTING CITY AS 'RAJKOT' IF NO CITY VALUE IS ENTERED DURING EMPLOYEE 
--INSERTION. 
	CREATE OR ALTER TRIGGER TR_DEFUALT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
	
		UPDATE EMPLOYEE
		SET CITY = 'RAJKOT'
		FROM EMPLOYEE E
		INNER JOIN inserted i
		ON E.EID = i.EID
		WHERE E.CITY IS NULL
	END;

	SELECT * FROM EMPLOYEE

	 INSERT INTO EMPLOYEE
	 VALUES (119 , 'JENISH' , 'BUSA' , 'IT' , 15000 , NULL , 'MALE' , 2028)

	

	
--8. CREATE TRIGGER FOR AUTOMATICALLY ADDING CURRENT YEAR IN JOININGYEAR IF NO VALUE IS ENTERED.

CREATE OR ALTER TRIGGER TR_DEFUALT_DATE
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
	
		UPDATE EMPLOYEE
		SET JOININGYEAR = YEAR(GETDATE())
		FROM EMPLOYEE E
		INNER JOIN inserted i
		ON E.EID = i.EID
		WHERE E.JOININGYEAR IS NULL
	END;

	SELECT * FROM EMPLOYEE

	 INSERT INTO EMPLOYEE
	 VALUES (117 , 'JENISH' , 'BUSA' , 'IT' , 15000 , 'RAJKOT' , 'MALE' , 2026)
--9. CREATE TRIGGER FOR PRINTING EMPLOYEE FULL NAME AFTER NEW EMPLOYEE INSERTION.

CREATE OR ALTER TRIGGER TR_PRINT_NAME
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
		SELECT FIRSTNAME + ' ' + LASTNAME FROM inserted
	END;

	
--10. CREATE TRIGGER FOR AUTOMATICALLY ASSIGNING DEPARTMENT AS ‘GENERAL’ IF DEPARTMENT VALUE IS NULL.
CREATE OR ALTER TRIGGER TR_DEFUALT_DEPARTMENT
	ON EMPLOYEE
	AFTER INSERT
	AS
	BEGIN
	
		UPDATE EMPLOYEE
		SET DEPARTMENT = 'GENERAL'
		FROM EMPLOYEE E
		INNER JOIN inserted i
		ON E.EID = i.EID
		WHERE E.DEPARTMENT IS NULL
	END;

	SELECT * FROM EMPLOYEE

	 INSERT INTO EMPLOYEE
	 VALUES (118 , 'JENISH' , 'BUSA' , NULL , 15000 , 'RAJKOT' , 'MALE' , 2026)


---------------------------------------------------------------------------------------------
								--EMPLOYEE_LOG TABLE
---------------------------------------------------------------------------------------------

CREATE TABLE EMPLOYEE_LOG
(
	EID INT,
	OLD_SALARY DECIMAL(9 , 2),
	NEW_SALARY DECIMAL(9 , 2),
	OLD_DEPARTMENT VARCHAR(30),
	NEW_DEPARTMENT VARCHAR(30),
	UPDATED_DATE DATE
)





--	 PART – C: 
--11. CREATE TRIGGER FOR STORING UPDATED EMPLOYEE DETAILS SUCH AS EID, OLD SALARY, NEW SALARY, OLD DEPARTMENT, 
--NEW DEPARTMENT, AND UPDATE DATE INTO EMPLOYEE_UPDATE_LOG TABLE. 

	CREATE OR ALTER TRIGGER TR_EMPLOYEE_LOG
	ON EMPLOYEE
	AFTER UPDATE
	AS
	BEGIN
		INSERT INTO EMPLOYEE_LOG 
		(EID, OLD_SALARY, NEW_SALARY, OLD_DEPARTMENT, NEW_DEPARTMENT, UPDATED_DATE)
    
		SELECT 
			D.EID,
			D.SALARY,
			I.SALARY,
			D.DEPARTMENT,
			I.DEPARTMENT,
			GETDATE()
		FROM deleted D
		INNER JOIN inserted I
        ON D.EID = I.EID;
	END
 
	UPDATE EMPLOYEE
	SET DEPARTMENT = 'SERVER'
	WHERE EID = 118
	SELECT * FROM EMPLOYEE

	SELECT * FROM EMPLOYEE_LOG
--12. CREATE TRIGGER FOR STORING NEWLY INSERTED EMPLOYEE DETAILS WITH INSERTION DATE INTO 
--EMPLOYEE_INSERT_LOG TABLE.

CREATE TRIGGER TR_EMPLOYEE_INSERT_LOG
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE_INSERT_LOG
    (EID, NAME, SALARY, DEPARTMENT, INSERT_DATE)
    
    SELECT
        EID,
        NAME,
        SALARY,
        DEPARTMENT,
        GETDATE()
    FROM inserted;
END;


--13. CREATE TRIGGER FOR STORING OLD AND NEW FIRSTNAME VALUES AFTER EMPLOYEE NAME UPDATE INTO 
--NAME_CHANGE_LOG TABLE.

CREATE TRIGGER TR_NAME_CHANGE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    INSERT INTO NAME_CHANGE_LOG
    (EID, OLD_FIRSTNAME, NEW_FIRSTNAME, CHANGE_DATE)
    SELECT
        D.EID,
        D.FIRSTNAME,
        I.FIRSTNAME,
        GETDATE()
    FROM deleted D
    INNER JOIN inserted I
        ON D.EID = I.EID;
END;
--14. CREATE TRIGGER FOR STORING OLD CITY AND NEW CITY DETAILS INTO CITY_UPDATE_LOG TABLE AFTER CITY UPDATE.

CREATE TRIGGER TR_CITY_UPDATE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    INSERT INTO CITY_UPDATE_LOG
    (EID, OLD_CITY, NEW_CITY, UPDATE_DATE)
    SELECT
        D.EID,
        D.CITY,
        I.CITY,
        GETDATE()
    FROM deleted D
    INNER JOIN inserted I
        ON D.EID = I.EID;
END;
--15. IMPLEMENT INSTEAD OF INSERT TRIGGER ON EMPLOYEE TABLE TO AUTOMATICALLY REMOVE EXTRA SPACES FROM 
--FIRSTNAME AND LASTNAME BEFORE INSERTION. 

CREATE TRIGGER TR_EMPLOYEE_SPACE
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO EMPLOYEE
    (EID, FIRSTNAME, LASTNAME, CITY, SALARY, DEPARTMENT)
    SELECT
        EID,
        LTRIM(RTRIM(FIRSTNAME)),
        LTRIM(RTRIM(LASTNAME)),
        CITY,
        SALARY,
        DEPARTMENT
    FROM inserted;
END;
